- .github/workflows/checks.yml
- .go-tools
- .pre-commit-config.yaml
- .tool-versions
- README.md
- hack/common.sh
- hack/kind/create-cluster.sh
- hack/kind/kind-base-config.yaml
- make/all.mk
- make/clusterctl.mk
- make/dev.mk
- make/go.mk
- make/kind.mk
- make/repo.mk
- make/tools.mk
Running `make dev.run-on-kind` will start a KinD cluster, use `clusterctl` to deploy
relevant providers, build Docker images, copy to the KinD cluster, and deploy
the extensions via Helm.
> build: Add make recipes for deploying local builds

- .github/workflows/checks.yml
- charts/capi-runtime-extensions/templates/clusterrole.yaml
- make/clusterctl.mk
- pkg/addons/crs.go
- pkg/addons/templates/cni/calico-cni-installation-crs.yaml
- pkg/addons/templates/cni/docker-calico-cni-installation-configmap.yaml
- pkg/handlers/lifecycle/handlers.go
- pkg/k8s/client/client.go
Missing variable reader when using clusterctl templating functions.
Tested via:
```shell
make dev.run-on-kind
eval $(make kind.kubeconfig)
clusterctl generate cluster capi-quickstart --flavor development --kubernetes-version v1.26.0 --control-plane-machine-count=1 --worker-machine-count=1 | k apply -f -
watch -n 1 clusterctl describe cluster capi-quickstart
k label cluster capi-quickstart capi-runtime-extensions.d2iq-labs.com/cni=calico
k get clusterresourcesetbindings.addons.cluster.x-k8s.io capi-quickstart
clusterctl get kubeconfig capi-quickstart > capd-kubeconfig
k --kubeconfig capd-kubeconfig get installations
```
Calico still doesn't work properly (PodSecurity issues) but this is good to merge.
Requires #11.
> fix: Fix panic when applying CNI CRS via hook

- go.mod
- go.sum
- pkg/constants/constants.go
- pkg/handlers/lifecycle/handlers.go
- pkg/k8s/annotations/annotations.go
- pkg/k8s/deleter/deleter.go
- pkg/k8s/deleter/deleter_test.go
Fixes https://github.com/d2iq-labs/capi-runtime-extensions/issues/4
Automatically delete workload cluster Services with type `LoadBalancers` before deleting the cluster.
It checks for certain conditions on the Cluster object if Services should be deleted.
It's also possible to disable this behavior by adding an annotation `capi-runtime-extensions.d2iq-labs.com/loadbalancer-gc` to the Cluster object.
> feat: delete Services type LoadBalancer on BeforeClusterDelete

- pkg/k8s/parser/parser.go
- pkg/k8s/parser/parser_test.go
This will be used in embedding YAML resources for the deployment.
> feat: Reintroduce manifest parser

- pkg/capi/clustertopology/patches/matchers/match.go
- pkg/capi/clustertopology/patches/matchers/match_test.go
- pkg/capi/clustertopology/variables/variable.go
- pkg/capi/clustertopology/variables/variables_test.go
- pkg/handlers/httpproxy/inject.go
Tests currently failing, fixing up in follow up commits.- refactor: Move matchers to own package and add tests.
> refactor: Move matchers to own package and add tests

- charts/capi-runtime-extensions/templates/role.yaml
- cmd/capi-runtime-extensions/main.go
- docs/content/http-proxy.md
- pkg/handlers/httpproxy/inject.go
- pkg/handlers/httpproxy/inject_test.go
- pkg/handlers/httpproxy/systemd_proxy_config.go
- pkg/handlers/httpproxy/systemd_proxy_config_test.go
- pkg/handlers/httpproxy/variables.go
- pkg/handlers/httpproxy/variables_test.go
Implements https://github.com/d2iq-labs/capi-runtime-extensions/issues/30
Example of generated values:
```
[Service]
Environment="HTTP_PROXY=http://example.com"
Environment="http_proxy=http://example.com"
Environment="NO_PROXY=localhost,127.0.0.1,192.168.0.0/16,10.128.0.0/12,kubernetes,kubernetes.default,.svc,.svc,.svc.cluster,.svc.cluster.
local,no-1.example.com"
Environment="no_proxy=localhost,127.0.0.1,192.168.0.0/16,10.128.0.0/12,kubernetes,kubernetes.default,.svc,.svc,.svc.cluster,.svc.cluster.
local,no-1.example.com"
```
> feat: calculate default no_proxy values based on cluster

- pkg/handlers/httpproxy/inject.go
- pkg/handlers/httpproxy/inject_test.go
Adds infra-specific exceptions to `no_proxy`. This should wrap up https://github.com/d2iq-labs/capi-runtime-extensions/issues/30
> feat: Support infra-specific httpproxy patches

- common/pkg/server/server.go
This means it will always run even if there are multiple replicas running. Leader election is only really useful for controllers, not for webhooks.
> fix: Do not require leader election for CAPI hooks server

- pkg/handlers/auditpolicy/inject.go
Match the other handlers and the docs https://github.com/d2iq-labs/capi-runtime-extensions/blob/main/docs/content/audit-policy.md
> fix: incorrect audit policy handler name

- .github/workflows/checks.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependabot-automation.yaml
- .github/workflows/github-pages.yml
- .github/workflows/release-tag.yaml
- .gitlint
Enables detection of failing bash pipelines:
> When shell: bash is specified, -o pipefail is also applied to
> enforce early exit from pipelines that generate a non-zero exit status.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
> ci: Explicitly specify bash as shell for GHA run steps

- cmd/main.go
- common/pkg/capi/clustertopology/handlers/mutation/meta.go
- pkg/handlers/clusterconfig/variables.go
- pkg/handlers/clusterconfig/variables_test.go
- pkg/handlers/cni/calico/handler.go
- pkg/handlers/etcd/inject.go
- pkg/handlers/etcd/inject_test.go
- pkg/handlers/etcd/variables.go
- pkg/handlers/etcd/variables_test.go
- pkg/handlers/extraapiservercertsans/inject.go
- pkg/handlers/extraapiservercertsans/inject_test.go
- pkg/handlers/extraapiservercertsans/variables.go
- pkg/handlers/extraapiservercertsans/variables_test.go
- pkg/handlers/httpproxy/inject.go
- pkg/handlers/httpproxy/inject_test.go
- pkg/handlers/httpproxy/variables.go
- pkg/handlers/httpproxy/variables_test.go
- pkg/handlers/kubernetesimagerepository/inject.go
- pkg/handlers/kubernetesimagerepository/inject_test.go
- pkg/handlers/kubernetesimagerepository/variables.go
- pkg/handlers/kubernetesimagerepository/variables_test.go
- pkg/handlers/metadata.go
When adding new handlers I kept forgetting to add it to the meta hander. Although this commit doesn't really solve it does make it easier to visually see a difference. It also simplifies adding handlers to the server by not asking for a package variable when calling `<patchpackage>.NewPatch()`.
Ideally we should be able to automatically build the metahandler from `patchHandlers` but I didn't see how to do that with the 2 interfaces we have now `Named` and `GeneratePatches`.
> refactor: how handlers are added to server

- cmd/main.go
Structured this in the same way as the AWS handlers.
> fix: bring back missing docker handlers

- common/pkg/capi/clustertopology/handlers/mutation/meta.go
- common/pkg/capi/clustertopology/handlers/mutation/meta_test.go
- pkg/handlers/aws/mutation/metapatch_handler.go
- pkg/handlers/aws/mutation/region/inject.go
- pkg/handlers/docker/mutation/customimage/inject.go
- pkg/handlers/docker/mutation/metapatch_handler.go
- pkg/handlers/generic/mutation/auditpolicy/inject.go
- pkg/handlers/generic/mutation/etcd/inject.go
- pkg/handlers/generic/mutation/extraapiservercertsans/inject.go
- pkg/handlers/generic/mutation/handlers.go
- pkg/handlers/generic/mutation/httpproxy/inject.go
- pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
- pkg/handlers/generic/mutation/kubernetesimagerepository/inject.go
Also fixes my typo in `mutater` to `mutator`.
> refactor: Use consistent decoder in mutators

- api/v1alpha1/docker_clusterconfig_types.go
Found typo while going through the code.
> fix: typo in docker cluster config api

- .pre-commit-config.yaml
This will be important in 2024...
> build: Allow past year in license header

- charts/capi-runtime-extensions/defaultclusterclasses/aws-cluster-class.yaml
- hack/examples/sync.sh
- make/clusterctl.mk
Extracting the external cloud provider fix from #192. I noticed some other issues (e.g. CNI ingress rules) and will push some follow up PRs too, but wanted to get this in separately so we can actually create AWS clusters (totally broken right now).
> fix: Correctly set external cloud provider for AWS

- common/pkg/testutils/capitest/request/items.go
- pkg/handlers/aws/mutation/cni/calico/inject.go
- pkg/handlers/aws/mutation/cni/calico/tests/generate_patches.go
- pkg/handlers/aws/mutation/metapatch_handler.go
- pkg/handlers/aws/mutation/metapatch_handler_test.go
- pkg/handlers/docker/mutation/metapatch_handler_test.go
This fixes 2 problems:
- handler was not registered in AWS meta patch handler
- handler was not updated to use `clusterConfig.addons.cni` when CNI config was moved under addons property
> fix: Ensure CNI ingress rules are added to AWSCluster

- pkg/handlers/generic/mutation/httpproxy/inject.go
> fix: Reduce log verbosity for http proxy variable not found

- .golangci.yml
- api/v1alpha1/clusterconfig_types.go
- common/pkg/testutils/capitest/request/items.go
- pkg/handlers/aws/clusterconfig/variables_test.go
- pkg/handlers/aws/mutation/iaminstanceprofile/inject_worker.go
- pkg/handlers/aws/mutation/iaminstanceprofile/tests/generate_patches.go
- pkg/handlers/aws/mutation/instancetype/inject_control_plane.go
- pkg/handlers/aws/mutation/instancetype/inject_worker.go
- pkg/handlers/aws/mutation/instancetype/tests/generate_patches.go
- pkg/handlers/generic/lifecycle/csi/aws-ebs/handler.go
- pkg/handlers/generic/lifecycle/csi/handler.go
- pkg/handlers/generic/lifecycle/csi/handler_test.go
Without this, the reviewdog/action-golangci-lint action can give false
positives. See reviewdog/action-golangci-lint#27
for details.
This occurred in a GHA run in
https://github.com/d2iq-labs/capi-runtime-extensions/actions/runs/6451051901/job/17511173049?pr=192#step:5:88.
Second commit refactors code to satisfy linters.
> build: Increase golangci-lint timeout for slower GHA runners

- common/go.mod
- common/pkg/capi/clustertopology/handlers/mutation/meta.go
- common/pkg/capi/clustertopology/handlers/mutation/meta_test.go
- common/pkg/capi/clustertopology/patches/generator.go
- common/pkg/capi/clustertopology/patches/generator_test.go
- examples/capi-quick-start/aws-cluster-ami.yaml
- pkg/handlers/aws/mutation/cni/calico/inject.go
- pkg/handlers/aws/mutation/iaminstanceprofile/inject_control_plane.go
- pkg/handlers/aws/mutation/iaminstanceprofile/inject_worker.go
- pkg/handlers/aws/mutation/instancetype/inject_control_plane.go
- pkg/handlers/aws/mutation/instancetype/inject_worker.go
- pkg/handlers/aws/mutation/metapatch_handler.go
- pkg/handlers/aws/mutation/region/inject.go
- pkg/handlers/docker/mutation/customimage/inject_control_plane.go
- pkg/handlers/docker/mutation/customimage/inject_worker.go
- pkg/handlers/docker/mutation/metapatch_handler.go
- pkg/handlers/generic/mutation/auditpolicy/inject.go
- pkg/handlers/generic/mutation/etcd/inject.go
- pkg/handlers/generic/mutation/extraapiservercertsans/inject.go
- pkg/handlers/generic/mutation/httpproxy/inject.go
- pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
- pkg/handlers/generic/mutation/kubernetesimagerepository/inject.go
- pkg/handlers/patches.go
This produces a minimal patch output by converting back and forth between real types and unstructured. See `patches.MutateIfApplicable` (renamed `patches.GeneratePatches`) function for comments on what is happening. The fact that I haven't had to change existing test contents gives me confidence that this works well.
> refactor: Always use unstructured in patch generators

- api/v1alpha1/aws_clusterconfig_types.go
- examples/capi-quick-start/aws-cluster.yaml
- hack/examples/bases/aws/kustomization.yaml.tmpl
AWS region should not be required as it can be set in the ClusterClass. Making it optional and setting it in the example instead. It also doesn't really make sense to have a default in the code for a region since there is no "default".
> fix: Don't set AWS region as required

- README.md
- adds [colima](https://github.com/abiosoft/colima) to devbox
- uses local instance of container runtime supported by colima to run kind cluster and build container images
Tested on M3 Mac:
```
❯ make dev.run-on-kind
INFO[0000] starting colima
INFO[0000] runtime: docker
INFO[0000] creating and starting ...                     context=vm
INFO[0033] provisioning ...                              context=docker
INFO[0033] starting ...                                  context=docker
INFO[0034] done
▶ creating kind cluster - capi-runtime-extensions-dev
Creating cluster "capi-runtime-extensions-dev" ...
✓ Ensuring node image (ghcr.io/mesosphere/kind-node:v1.27.5) 🖼
✓ Preparing nodes 📦
✓ Writing configuration 📜
✓ Starting control-plane 🕹️
✓ Installing CNI 🔌
✓ Installing StorageClass 💾
Set kubectl …
```
> build: local development in macOS(and Linux) arm64/amd64 using local colima instance

- .golangci.yml
- pkg/handlers/generic/mutation/imageregistries/credentials/tests/generate_patches.go
Noticed this was disabled, but would prefer to always explicitly
check errors even, or rather especially, in tests.
> build: Lint for missed errors in tests too

- pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files.go
- pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files_test.go
- pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_install_files.go
- pkg/handlers/generic/mutation/imageregistries/credentials/templates/dynamic-credential-provider-config.yaml.gotmpl
- pkg/handlers/generic/mutation/imageregistries/credentials/templates/kubelet-image-credential-provider-config.yaml.gotmpl
- pkg/handlers/generic/mutation/imageregistries/credentials/templates/static-credential-provider.json.gotmpl
Required to fully support latest kubelet credential providers prior to merging #292.
> feat: Use latest dynamic credential provider and v1 kubelet API

- README.md
Chose the CAAPH example as that is the one we want to eventually move to. Tested locally.
> docs: fix cluster name in README

- api/v1alpha1/clusterconfig_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
- pkg/handlers/generic/mutation/imageregistries/credentials/tests/generate_patches.go
- pkg/handlers/generic/mutation/imageregistries/credentials/variables_test.go
- pkg/handlers/generic/mutation/mirrors/mirror.go
- pkg/handlers/generic/mutation/mirrors/mirror_test.go
- pkg/handlers/generic/mutation/mirrors/tests/generate_patches.go
- pkg/handlers/generic/mutation/mirrors/variables_test.go
Using `LocalObjectReference` ensures user cannot override the secret namespace.
Fixes #322.
> fix: Ensure registry credentials are namespace local to Cluster

- .github/workflows/release-please.yaml
- capi-runtime-extensions.code-workspace
This enables it to be imported directly into other Go projects.
Follow up to #331.
> ci: Tag api module on release

- README.md
- make/dev.mk
Added a new Makefile target to just build and redeploy the webhook on an existing kind cluster.
This target is useful when testing bug fixes in downstream projects.
> test: add a Makefile target to update image

- .golangci.yml
- common/pkg/testutils/capitest/patches.go
- pkg/handlers/aws/mutation/ami/inject.go
- pkg/handlers/aws/mutation/ami/tests/generate_patches.go
If empty CAPA will fail with:
```
failed to create AWSMachine instance: failed to run instance: MissingParameter: The request must contain the parameter ImageId
```
> fix: AMI ID patch

- charts/capi-runtime-extensions/templates/csi/aws-ebs/manifests/aws-ebs-csi-configmap.yaml
- hack/addons/kustomize/aws-ebs-csi/kustomization.yaml.tmpl
The manifests in the upstream CSI repos may not have the correct images set.
Override the image to match the expected version.
Because of the mismatch between the image and the specs, the EBS CSI deployment failed with:
```
kubectl logs -n kube-system ebs-csi-controller-5564c47bd7-wphl2 
Defaulted container "ebs-plugin" out of: ebs-plugin, csi-provisioner, csi-attacher, csi-snapshotter, csi-resizer, liveness-probe
unknown flag: --batching
```
> fix: use correct AWS EBS CSI images

- pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files.go
- pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files_test.go
- pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
- pkg/handlers/generic/mutation/imageregistries/credentials/templates/dynamic-credential-provider-config.yaml.gotmpl
- pkg/handlers/generic/mutation/mirrors/mirror.go
Fixes : https://github.com/d2iq-labs/capi-runtime-extensions/issues/329 (Support for mirror credentials for "globalImageRegistryMirror")
- Adds `mirror` configuration in DynamicCredentialsConfig
e.g.
```
apiVersion: credentialprovider.d2iq.com/v1alpha1
kind: DynamicCredentialProviderConfig
mirror:
endpoint: mymirror.com
credentialsStrategy: MirrorCredentialsOnly
credentialProviderPluginBinDir: /etc/kubernetes/image-credential-provider/
...
```
- reads mirror credentials from secret and add its provider configuration in DynamiCredentialsProviderConfig if provided
e.g.
```
apiVersion: credentialprovider.d2iq.com/v1alpha1
kind: DynamicCredentialProviderConfig
mirror:
endpoint: mymirror.com
credentialsStrategy: MirrorCredentialsOnly
credentialProviderPluginBinDir: …
```
> fix: mirror credentials support in DynamicCredentialProviderConfig

- pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_install_files.go
- pkg/handlers/generic/mutation/imageregistries/credentials/tests/generate_patches.go
The word "konvoy" doesn't mean anything in this repo, renamed it to more generic "cre".
We can rename it to something else if this repo is renamed in future.
> fix: remove word konvoy/ and use cre/

- pkg/handlers/generic/mutation/mirrors/mirror.go
- pkg/handlers/generic/mutation/mirrors/mirror_test.go
- pkg/handlers/generic/mutation/mirrors/templates/hosts.toml.gotmpl
Found a bug(?) in how Containerd handles mirrors with a path and it incorrectly appends `/v2` to the end of mirror, and not between the provided host and path.
See https://github.com/containerd/containerd/issues/6634#issuecomment-1944899130 for a longer explanation and example output.
> fix: v2/ in Containerd mirror path

- pkg/handlers/generic/mutation/mirrors/inject.go
- pkg/handlers/generic/mutation/mirrors/mirror.go
- pkg/handlers/generic/mutation/mirrors/mirror_test.go
- pkg/handlers/generic/mutation/mirrors/templates/containerd-apply-patches.sh.gotmpl
- pkg/handlers/generic/mutation/mirrors/templates/containerd-registry-config-drop-in.toml
- pkg/handlers/generic/mutation/mirrors/tests/generate_patches.go
Set `config_path ` in the Containerd config as described in https://github.com/containerd/containerd/blob/main/docs/hosts.md#cri
~This is not enough, we also need to remove `registry.mirrors` from the config file, opening in case @jimmidyson you have some ideas on how we can do this, [TOML doesn't have a nil value](https://github.com/toml-lang/toml/issues/30)~:
```
Feb 15 05:59:13 docker-quick-start-helm-addon-cilium-rjfjv-hn9m7 containerd[7127]: time="2024-02-15T05:59:13.663662461Z" level=warning msg="failed to load plugin io.containerd.grpc.v1.cri" error="invalid plugin config: `mirrors` cannot be set when `config_path` is provided"
```
No additional changes are needed, the unnecessary mirror configuration will be removed from the OS image instead.
> fix: set config_path in Containerd config

- api/v1alpha1/zz_generated.deepcopy.go
- pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files.go
- pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files_test.go
- pkg/handlers/generic/mutation/imageregistries/credentials/credentialprovider/matcher.go
- pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
- pkg/handlers/generic/mutation/imageregistries/credentials/inject_test.go
Follow up to https://github.com/d2iq-labs/capi-runtime-extensions/pull/359
I noticed that when the only setting `globalImageRegistryMirror` without `imageRegistries` that the credential provider configs were not being generated.
Tested locally and verified in the Docker container :
```
kubectl get kubeadmconfig.bootstrap.cluster.x-k8s.io/docker-quick-start-helm-addon-cilium-dgz8d-dk7c5 -o yaml | grep "path:"
audit-log-path: /var/log/audit/kube-apiserver-audit.log
path: /etc/kubernetes/audit-policy/apiserver-audit-policy.yaml
path: /etc/konvoy/install-kubelet-credential-providers.sh
path: /etc/kubernetes/image-credential-provider-config.yaml
path: /etc/kubernetes/dynamic-credential-provider-config.yaml
path: /etc/kubernetes/static-image-credentials.json
path: …
```
> fix: generate config with only globalImageRegistryMirror set

- .pre-commit-config.yaml
- README.md
- api/v1alpha1/clusterconfig_types.go
- docs/content/addons/calico-cni.md
- examples/capi-quick-start/aws-cluster-calico-crs.yaml
- examples/capi-quick-start/aws-cluster-calico-helm-addon.yaml
- examples/capi-quick-start/aws-cluster-cilium-crs.yaml
- examples/capi-quick-start/aws-cluster-cilium-helm-addon.yaml
- examples/capi-quick-start/aws-cluster-identity.yaml
- examples/capi-quick-start/docker-cluster-calico-crs.yaml
- examples/capi-quick-start/docker-cluster-calico-helm-addon.yaml
- examples/capi-quick-start/docker-cluster-cilium-crs.yaml
- examples/capi-quick-start/docker-cluster-cilium-helm-addon.yaml
- hack/examples/bases/aws/calico/crs/kustomization.yaml.tmpl
- hack/examples/bases/aws/calico/helm-addon/kustomization.yaml.tmpl
- hack/examples/bases/aws/cilium/crs/kustomization.yaml.tmpl
- hack/examples/bases/aws/cilium/helm-addon/kustomization.yaml.tmpl
- hack/examples/bases/aws/kustomization.yaml.tmpl
- hack/examples/bases/docker/calico/crs/kustomization.yaml.tmpl
- hack/examples/bases/docker/calico/helm-addon/kustomization.yaml.tmpl
- hack/examples/bases/docker/cilium/crs/kustomization.yaml.tmpl
- hack/examples/bases/docker/cilium/helm-addon/kustomization.yaml.tmpl
- hack/examples/bases/docker/kustomization.yaml.tmpl
- hack/examples/kustomization.yaml.tmpl
- hack/examples/sync.sh
- pkg/handlers/generic/lifecycle/cpi/handler.go
- pkg/handlers/generic/lifecycle/handlers.go
Provides easier integration with CAPI e2e testing libraries.
> docs: Update examples to be clusterctl templates

- api/v1alpha1/zz_generated.deepcopy.go
A change to an auotgenerated file that is [breaking the release](https://github.com/d2iq-labs/capi-runtime-extensions/actions/runs/7921983815) snuck in here https://github.com/d2iq-labs/capi-runtime-extensions/pull/362
> fix: revert back generated file changes

- pkg/handlers/generic/mutation/mirrors/inject.go
- pkg/handlers/generic/mutation/mirrors/mirror.go
- pkg/handlers/generic/mutation/mirrors/templates/containerd-restart.sh
- pkg/handlers/generic/mutation/mirrors/tests/generate_patches.go
>Updates under this directory do not require restarting the containerd daemon.
Even-though [a restart is not required ](https://github.com/containerd/containerd/blob/main/docs/hosts.md#registry-configuration---introduction) on changes, it is still required initially after setting `config_path` in the Containerd config.
---
Tested locally with a CAPD cluster:
```
root@docker-quick-start-helm-addon-cilium-ng7q8-7xcrh:/# journalctl -u containerd | grep starting
Feb 16 01:42:07 docker-quick-start-helm-addon-cilium-ng7q8-7xcrh containerd[129]: time="2024-02-16T01:42:07.338020972Z" level=info msg="starting containerd" revision=1677a17964311325ed1c31e2c0a3589ce6d5c30d version=v1.7.1
Feb 16 01:42:17 docker-quick-start-helm-addon-cilium-ng7q8-7xcrh containerd[495]: …
```
> fix: restart Containerd when setting mirror config

- go.mod
- test/e2e/config/cre.yaml
- test/e2e/e2e_suite_test.go
- test/framework/clusterctl/e2e_config.go
- test/framework/goproxy/goproxy.go
Copied functionality from cluster-api repo main branch until it is released
in next minor (v1.7) when we can remove this functionality and switch
back to upstream.
Depends on #383.
Temporary implementation for #386.
> test(e2e): Resolve latest upstream provider releases in e2e config

- make/clusterctl.mk
v2.3.4 release was partially done and then rolled back. This has broken the
discovery mechanism built in to clusterctl which uses go mod proxy to
discover latest releases of providers. Seeing errors in other builds, e.g.
https://github.com/d2iq-labs/capi-runtime-extensions/actions/runs/8029367117/job/21942031279?pr=390#step:9:10
```
Error: failed to get provider components for the "aws" provider: failed to
get repository client for the InfrastructureProvider with name aws: error
creating the GitHub repository client: failed to get latest release:
release not found for version v2.3.4, please retry later or set "GOPROXY=off"
to get the current stable release: 404 Not Found
```
Disabling GOPROXY temporarily until CAPA release is fixed.
> test: Temporarily disable GOPROXY to workaround dodgy CAPA release

- test/e2e/clusterresourceset_helpers.go
Upstream PR https://github.com/kubernetes-sigs/cluster-api/pull/10191
> test(e2e): Find specific CRS binding when checking if resource is applied

- test/e2e/e2e_suite_test.go
- test/e2e/e2e_suite_vars.go
- test/framework/bootstrap/kindprovider.go
This allows configuration of k8s versions, etc via flags.
Fixes #387.
> test(e2e): Use ghcr.io/mesosphere/kind-node for bootstrap

- charts/capi-runtime-extensions/templates/deployment.yaml
Previous helm deployment would look in default namespace which broke
things.
> fix: Ensure addons defaults namespaces are correctly wired up

- make/clusterctl.mk
This reverts commit 41a6cb9d49a4f163b8524414de857955c747c6e3.
CAPA release v2.3.5 has successfully released so we can revert this now.
> revert: Temporarily disable GOPROXY to workaround dodgy CAPA release (#395)

- hack/addons/kustomize/aws-ebs-csi/kustomization.yaml.tmpl
- hack/addons/kustomize/cilium/kustomization.yaml.tmpl
- hack/addons/kustomize/nfd/kustomization.yaml.tmpl
- hack/addons/kustomize/tigera-operator/kustomization.yaml.tmpl
Otherwise `{{.Release.Namespace}}` used in helm chart inflation is set
to `default` which can affect template output.
> build: Ensure release namespace is use in kustomize helm inflator

- charts/capi-runtime-extensions/README.md
- charts/capi-runtime-extensions/templates/deployment.yaml
- charts/capi-runtime-extensions/values.yaml
This webhook is on the critical path of all cluster lifecycle operations. Setting default priorityClassName to system-cluster-critical, to increase the chances of this Deployment running when there is resource contention.
> fix: set default priorityClassName on Deployment

- charts/capi-runtime-extensions/README.md
- charts/capi-runtime-extensions/values.yaml
This webhook is on the critical path of all cluster lifecycle operations. Add tolerations to allow it to run on the control-plane Nodes, and be able to recover the cluster if all workers were deleted.
> fix: set default tolerations on Deployment

- hack/third-party/capd/go.mod
- hack/third-party/capd/go.sum
Should be the same as the test go module dependency, but this is
only a vanity thing to do, it does not break anything.
> build: Fix up third-party CAPD go.mod CAPI dependency

- .github/workflows/dependabot-automation.yml
- .github/workflows/devbox-update.yml
This is disallowed by GH org settings.
> ci: Remove auto-approve PR steps

- pkg/handlers/generic/mutation/httpproxy/tests/generate_patches.go
The "generic worker" test case already covers this.
> test: Remove redundant test case from httpproxy handler

- .github/workflows/github-pages.yml
Grouping on PR number or git ref (branch or tag). Without this all pages
builds were included in the same concurrency group, meaning that concurrent
PR builds were leading to skipped workflows. As this is a required check, that
meant that PRs could not be merged without opening/closing the PR - not a
fun thing to have to do!
> ci: Fix pages workflow concurrency

- .golangci.yml
- go.mod
- go.sum
- test/e2e/e2e_suite_test.go
- test/e2e/helmreleaseproxy_helpers.go
Also introduces linting rules to prevent happening this in future.
> refactor: Replace direct usage of CAAPH API with vendored types

- api/v1alpha1/aws_node_types.go
- api/v1alpha1/clusterconfig_types.go
- api/v1alpha1/node_types.go
- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/aws-cluster-class.yaml
- hack/examples/overlays/clusterclasses/aws/kustomization.yaml.tmpl
- pkg/handlers/aws/clusterconfig/variables.go
- pkg/handlers/aws/mutation/ami/variables_test.go
- pkg/handlers/aws/mutation/controlplaneloadbalancer/variables_test.go
- pkg/handlers/aws/mutation/iaminstanceprofile/variables_test.go
- pkg/handlers/aws/mutation/instancetype/variables_test.go
- pkg/handlers/aws/mutation/network/variables_test.go
- pkg/handlers/aws/mutation/region/variables_test.go
- pkg/handlers/aws/mutation/securitygroups/variables_test.go
- pkg/handlers/aws/workerconfig/variables.go
- pkg/handlers/aws/workerconfig/variables_test.go
Moved https://github.com/d2iq-labs/cluster-api-runtime-extensions-nutanix/pull/51 
Addressed the pending review comments
**What problem does this PR solve?:**
- sets defaults for aws nodes CP: m5.xlarge and Workers: m5.2xlarge
- sets PLACEHOLDER value as defaults in AWSMachineTemplates because instanceType field is required by CAPA.
- sets instance type as required field in the schema since CAREN will be using the default if not provided by the user.
update existing unit tests to use default schema
**NOTE**
Once this PR is finalized, I will create follow up PR to set instance profile and some other changes in the API types that would ensure that it creates variable schema from the object instead of creating new one.
**Which issue(s) this PR fixes:**
Fixes # …
> fix: set defaults for AWS CP and Worker instanceType

- examples/capi-quick-start/nutanix-cluster-calico-crs.yaml
- examples/capi-quick-start/nutanix-cluster-calico-helm-addon.yaml
- examples/capi-quick-start/nutanix-cluster-cilium-crs.yaml
- examples/capi-quick-start/nutanix-cluster-cilium-helm-addon.yaml
- hack/examples/additional-resources/dockerhub-secret.yaml
- hack/examples/bases/nutanix/cluster/kustomization.yaml.tmpl
- hack/examples/patches/dockerhub-image-registry.yaml
Adding dockerhub credentials in the examples, to make it easier to bring up Nutanix clusters. Otherwise, the limit is hit for almost every cluster.
> build: set dockerhub credentials for Nutanix examples

- api/v1alpha1/aws_node_types.go
- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/aws-cluster-class.yaml
- hack/examples/overlays/clusterclasses/aws/kustomization.yaml.tmpl
Moved: https://github.com/d2iq-labs/cluster-api-runtime-extensions-nutanix/pull/54
**What problem does this PR solve?:**
This is a stacked PR: https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/504
sets defaults for aws instance profiles CP: `control-plane.cluster-api-provider-aws.sigs.k8s.io` and Workers: `nodes.cluster-api-provider-aws.sigs.k8s.io`
removes instanceProfile field in AWSMachineTemplates
**Which issue(s) this PR fixes:**
Fixes #
**How Has This Been Tested?:**
Tested manually be creating AWS cluster.
Created AWS cluster without adding instanceProfile variable, CAREN patched AWSMachineTemplate with default instanceProfile.
**Special notes for your reviewer:**
Looking into ways to unit test the defaults.
> feat: set default instance profile for AWS CP and worker nodes

- api/go.mod
- common/go.mod
- go.mod
Nix (and therefore devbox) has been slow in rolling out go1.22.2, which
contains CVE fixes. Current version go1.22.1 causes govulncheck to
report valid vulnerabilities in `net/http` package. go1.21 introduced
toolchain management via `go.mod` file with `toolchain` directive. This
commit specifies go1.22.2 as the toolchain to use and hence fixes the
govulncheck issues.
This does mean that go versions have to be managed in multiple places so
this is a stop-gap until Nix releases go1.22.2 to nixpkgs-unstable
channel.
> build: Specify go1.22.2 as toolchain to fix govulncheck issues

- metadata.yaml
- test/e2e/config/caren.yaml
- test/e2e/data/shared/v1beta1-caren/metadata.yaml
Also update e2e config to use v0.7.x for local CAREN builds.
> build: Add metadata for latest v0.7.0 release

- .golangci.yml
- cmd/main.go
- common/pkg/capi/apis/schemes.go
- common/pkg/capi/clustertopology/handlers/helpers.go
- common/pkg/testutils/capitest/patches.go
- pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_helmaddon.go
- pkg/handlers/generic/lifecycle/cni/calico/strategy_crs.go
- pkg/handlers/generic/lifecycle/cni/calico/strategy_helmaddon.go
- pkg/handlers/generic/lifecycle/cni/cilium/strategy_helmaddon.go
- pkg/handlers/generic/lifecycle/cni/cluster.go
- pkg/handlers/generic/lifecycle/nfd/strategy_helmaddon.go
- pkg/handlers/generic/mutation/httpproxy/inject.go
- pkg/handlers/generic/mutation/httpproxy/inject_test.go
- pkg/handlers/nutanix/mutation/controlplaneendpoint/inject.go
- test/e2e/addon_helpers.go
- test/e2e/clusterresourceset_helpers.go
- test/e2e/cni_helpers.go
- test/e2e/nfd_helpers.go
Pulling this change out from #514.
> refactor: Consistently import CAPI v1beta1 package as clusterv1 alias

- .goreleaser.yml
Previous releases incorrectly missed the `v` prefix in the image when
generating the `runtime-extensions-components.yaml`. This commit fixes
that always inculding the `v`.
This commit also ensures that the use of `trimprefix` to remove the
`v` prefix is consistently applied. As documented at
https://goreleaser.com/customization/templates/#fn:version-prefix, the
`Version` variable does not include the `v` prefix, but this is only for
releases, and the `v` prefix is actually included in `Version` for
snapshot or nightly builds.
> build: Fix image tags in release manifests

- test/e2e/config/caren.yaml
- test/e2e/data/shared/v1beta1-caaph/metadata.yaml
- test/e2e/e2e_suite_test.go
This provides a stable test setup for e2e that is unaffected by ongoing
upstream releases.
> test(e2e): Use same versions of providers from module dependencies

- .github/workflows/checks.yml
This makes it easier to see what golangci-lint checks have failed.
> ci: Add permissions to add PR review comments for reviewdog actions

- make/dev.mk
creates makefile target to update the expired aws credentials and restart capa-controller.
make dev.update-bootstrap-credentials-aws reads similar to our existing command dkp update bootstrap credentials aws
> build: update aws credentials on kind bootstrap cluster

- api/v1alpha1/addon_types.go
Im updating the version in Konvoy and noticed that it not added:
```
ccm:
credentials: null
```
Fixes #
I'll try to find some linter that can catch this in the future.
> fix: add omitempty to CCM Credentials struct

- charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/helm-addon-installation.yaml
- pkg/handlers/generic/lifecycle/ccm/aws/handler.go
- pkg/handlers/generic/lifecycle/ccm/handler.go
- pkg/handlers/generic/lifecycle/ccm/nutanix/handler.go
- pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_crs.go
- pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_helmaddon.go
- pkg/handlers/generic/lifecycle/cni/calico/strategy_helmaddon.go
- pkg/handlers/generic/lifecycle/cni/cilium/strategy_helmaddon.go
- pkg/handlers/generic/lifecycle/csi/aws-ebs/handler.go
- pkg/handlers/generic/lifecycle/csi/handler.go
- pkg/handlers/generic/lifecycle/csi/nutanix-csi/handler.go
- pkg/handlers/generic/lifecycle/nfd/strategy_helmaddon.go
- pkg/handlers/generic/lifecycle/utils/utils.go
I noticed there were 3 copies of `retrieveValuesTemplateConfigMap()` in addition to the one generic one in `lifecycleutils`, refactored all of these methods to reuse the existing function.
~While refactoring I saw that for NFD the handler was adding a value, moved the templating to the helm values. This copies the pattern in other addons, but also makes it easier to override at cluster creation time (kind of as a last resort if there is a bug in the handler code)~ Reverted in 5f24ee0e2acc99e383e021bc5203994fc53c2308, we don't get the standard`.Chart.Version` when CAAPH templates the values, will file a separate PR to gotemplate this in the handler.
I also added `RetrieveValuesTemplate` to get the data instead of having `valuesTemplateConfigMap.Data["values.yaml"]` in every handler.
> refactor: standardize the code for getting Helm values

- api/v1alpha1/clusterconfig_types.go
- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/docker-cluster-class.yaml
- common/pkg/capi/utils/utils.go
- hack/examples/bases/docker/clusterclass/kustomization.yaml.tmpl
- pkg/handlers/generic/mutation/extraapiservercertsans/inject.go
- pkg/handlers/generic/mutation/extraapiservercertsans/inject_test.go
https://jira.nutanix.com/browse/D2IQ-100340 Adds docker sans through mutation handler using the new functionality in #514 
Fixes #
Tested manually by creating a docker cluster.
Depends on #514.
> feat: get default sans via cluster object in patch handler for docker

- api/v1alpha1/clusterconfig_types.go
- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/nutanix-cluster-class.yaml
- hack/examples/bases/nutanix/clusterclass/kustomization.yaml.tmpl
- pkg/handlers/generic/mutation/extraapiservercertsans/inject.go
- pkg/handlers/generic/mutation/extraapiservercertsans/inject_test.go
https://jira.nutanix.com/browse/D2IQ-100519
> feat: adds nutanix SANs via patchHandler

- devbox.json
- docs/content/contributing/releasing.md
- hack/flakes/flake.nix
- make/dev.mk
Adds docs with details how to release.
Fixes #
> docs: Add how to release doc

- .envrc
- .gitignore
allows developers to have `.envrc.local` files to contain secret information like `NUTANIX_USER` and `NUTANIX_PASSWORD` 
based on this https://github.com/direnv/direnv/issues/544#issuecomment-598654584
Fixes #
> build: adds a .envrc.local file for local development for dotenv

- pkg/handlers/generic/lifecycle/csi/aws-ebs/handler.go
- pkg/handlers/generic/lifecycle/csi/nutanix-csi/handler.go
- pkg/handlers/generic/lifecycle/utils/scs.go
Removes our dependency for Cluster Resource Sets entirely for Nutanix Clusters
Create a cluster and check if storage class is created.
```sh
02:55 PM  faiqus @ archlinux  ~/go/src/github.com/d2iq-labs/cluster-api-runtime-extensions-nutanix  faiq/storageclass-direct? 
$ kubectl --kubeconfig=faiqcsi.conf get sc
NAME                       PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
nutanix-volume (default)   csi.nutanix.com   Delete          WaitForFirstConsumer   false                  3m
02:56 PM  faiqus @ archlinux  ~/go/src/github.com/d2iq-labs/cluster-api-runtime-extensions-nutanix  faiq/storageclass-direct? 
$ kubectl get clusterresourcesets
No …
```
> refactor: create storage classes directly instead of using CRS

- PROJECT
- api/v1alpha1/doc.go
- api/v1alpha1/groupversion_info.go
- docs/content/lifecycle/service-loadbalancer-gc.md
- pkg/handlers/generic/lifecycle/ccm/doc.go
- pkg/handlers/generic/lifecycle/csi/doc.go
> refactor: Move API to caren.nutanix.com group

- .envrc
- .gitignore
- make/dev.mk
Following up with https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/538 adds a helper makefile target that creates `.envrc.local` file from `test/e2e/config/caren.yaml`
This helps keeping the local env file in sync with changes in the e2e tests.
it also overriding env variables in `test/e2e/config/caren.yaml`
Fixes #
```
❯ make .envrc.local
direnv: loading ~/gitrepos/cluster-api-runtime-extensions-nutanix/.envrc
Info: New devbox available: 0.8.5 -> v0.10.5. Please run `devbox version update`.
direnv: using devbox
direnv: export +AR +AS +CAPI_DIAGNOSTICS_ADDRESS +CAPI_INSECURE_DIAGNOSTICS +CC +CLUSTER_TOPOLOGY 
... 
...
....
~KUBERNETES_VERSION ~PATH
❯ …
```
> build: create .envrc.e2e file from caren e2e config

- .github/dependabot.yml
This is because controller-runtime still requires 0.29.x dependencies
so cannot upgrde to 0.30.0.
> build: Only allow patch updates to k8s libs

- .golangci.yml
> build: Minor golangci-lint config updates for recent versions

- common/pkg/k8s/client/apply.go
- pkg/handlers/generic/lifecycle/ccm/aws/handler.go
- pkg/handlers/generic/lifecycle/ccm/nutanix/handler.go
- pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_crs.go
- pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_helmaddon.go
- pkg/handlers/generic/lifecycle/cni/calico/strategy_crs.go
- pkg/handlers/generic/lifecycle/cni/calico/strategy_helmaddon.go
- pkg/handlers/generic/lifecycle/cni/cilium/strategy_crs.go
- pkg/handlers/generic/lifecycle/cni/cilium/strategy_helmaddon.go
- pkg/handlers/generic/lifecycle/csi/aws-ebs/handler.go
- pkg/handlers/generic/lifecycle/csi/nutanix-csi/handler.go
- pkg/handlers/generic/lifecycle/nfd/strategy_crs.go
- pkg/handlers/generic/lifecycle/nfd/strategy_helmaddon.go
- pkg/handlers/generic/lifecycle/utils/scs.go
- pkg/handlers/generic/lifecycle/utils/secrets.go
- pkg/handlers/generic/lifecycle/utils/utils.go
- pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
We want to preserve user-managed fields when we create/update specific resources. If a value in a user-managed field conflicts with our value, we want to alert the user by returning an error, rather than overwriting the value.
This PR exposes the `ForceOwnership` option to callers, but does not change the behavior of existing callers. 
Fixes #
> feat: Preserve user-managed fields when applying resources

- pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_crs.go
- pkg/handlers/generic/lifecycle/utils/secrets.go
- pkg/handlers/generic/lifecycle/utils/utils.go
- pkg/handlers/generic/lifecycle/utils/utils_integration_test.go
- pkg/handlers/generic/lifecycle/utils/utils_suite_test.go
We want to ensure the namespace exists, while preserving user-managed fields (i.e. labels and annotations) namespace exists.
Currently, if the namespace already exists, we do not update it. This prevents us from applying our own labels and annotations to an existing namespace, something we need to do in certain cases. This PR allows us to, in a future PR, apply labels and annotations to an existing namespace.
Fixes #
I added a new integration (envtest-based) test that verifies the desired behavior.
Depends on #556.
> feat: Preserve user-managed fields when creating namespace

- .github/workflows/e2e.yml
- pkg/handlers/generic/lifecycle/csi/nutanix-csi/handler.go
- test/e2e/config/caren.yaml
- test/e2e/data/shared/v1beta1-capx/metadata.yaml
- test/e2e/ownerreference_helpers.go
- test/e2e/quick_start_test.go
We need to set following vars in either env or caren.yaml
NUTANIX_ENDPOINT: ""
NUTANIX_PORT: 9440
NUTANIX_INSECURE: false
NUTANIX_USER: ""
NUTANIX_PASSWORD: ""
CONTROL_PLANE_ENDPOINT_IP: ""
CONTROL_PLANE_ENDPOINT_PORT: 6443
NUTANIX_PRISM_ELEMENT_CLUSTER_NAME: ""
NUTANIX_MACHINE_TEMPLATE_IMAGE_NAME: ""
NUTANIX_SUBNET_NAME: ""
NUTANIX_STORAGE_CONTAINER_NAME: ""
DOCKER_HUB_USERNAME: ""
DOCKER_HUB_PASSWORD: ""
Adds Nutanix provider to quick start test
Fixes #https://jira.nutanix.com/browse/D2IQ-100400 
<pre>
make e2e-test
</pre>
> feat: Added e2e test for capx cluster

- .github/workflows/checks.yml
- .github/workflows/e2e.yml
- common/pkg/capi/utils/utils.go
- devbox.lock
- test/e2e/addon_helpers.go
- test/e2e/clusterautoscaler_helpers.go
- test/e2e/e2e_suite_test.go
- test/e2e/framework/self_hosted.go
- test/e2e/helmreleaseproxy_helpers.go
- test/e2e/nfd_helpers.go
- test/e2e/quick_start_test.go
- test/e2e/self_hosted_test.go
Creating as draft until kubernetes-sigs/cluster-api-addon-provider-helm#189 is merged and released.
Depends on #494.
> test(e2e): Add self-hosted e2e test

- .github/dependabot.yml
This has to be inline with controller-runtime dependencies so we
can rely on that upgrading to upgrade k8s.io/* dependencies.
> build: Bundle k8s.io/* back in with sigs.k8s.io/* dependencies 

- Makefile
- make/dev.mk
This enables running envtest based Ginkgo tests more easily in your terminal or
in vscode if you have the direnv plugin installed.
> build: Add envtest setup to e2e envrc

- devbox.lock
The release failed because of a dirty `git` state with `devbox.lock`. https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/actions/runs/8882515772/job/24387382324
Fixes #
> build: fix outdated devbox.lock file

- api/v1alpha1/addon_types.go
- api/v1alpha1/clusterconfig_types.go
- api/v1alpha1/common_types.go
- pkg/handlers/generic/lifecycle/ccm/handler.go
- pkg/handlers/generic/lifecycle/csi/handler.go
We have not explained how we use API constants. We also have good reasons to remove some constants. This PR does the former, and gets us closer to the latter.
Fixes #
> refactor: Clean up API constants, and explain usage

- pkg/handlers/generic/lifecycle/config/cm.go
Puts the namespace and name in the right order in a log message, and includes these in the corresponding error message, instead of a data value that's not human-readable.
Fixes #
> fix: Fix error messages returned by HelmChartGetter

- .markdownlint.json
- docs/content/_index.md
- docs/content/addons/_index.md
- docs/content/addons/cluster-autoscaler.md
- docs/content/contributing/_index.md
- docs/content/contributing/e2e_tests.md
- docs/content/contributing/releasing.md
- docs/content/customization/_index.md
- docs/content/customization/nutanix/_index.md
- docs/content/getting-started/_index.md
- docs/content/getting-started/deployment/_index.md
- docs/content/getting-started/deployment/via-clusterctl.md
- docs/content/getting-started/deployment/via-helm.md
- docs/content/lifecycle/_index.md
- docs/hugo.toml
Also add some more icon bling to the menu and update menu ordering.
> docs: Add how to deploy CAREN

- devbox.json
- devbox.lock
- docs/layouts/_internal/google_analytics_async.html
There is an incompatibility in docsy with latest hugo so follow
https://github.com/open-telemetry/opentelemetry.io/pull/4392/files to
workaround this.
Once a compatible version of docsy is released, we can delete the layout
override file.
> docs: Upgrade hugo to latest

- .gitignore
- .goreleaser.yml
When a new minor release is created, the metadata attached to the
release needs to include the release series provider compatibility
mapping. This commit ensures that if a new minor release is cut that the
`metadata.yaml` attached to the release is cotrect for that release.
I have manually fixed v0.8.1 and v0.7.0 releases and with this commit we
won't need to do it manually ever again!
> build: Ensure provider metadata is up to date when releasing

- .goreleaser.yml
- cluster-api-runtime-extensions-nutanix.code-workspace
- docs/content/getting-started/create-cluster/_index.md
- docs/content/getting-started/create-cluster/aws.md
- docs/content/getting-started/create-cluster/docker.md
- docs/content/getting-started/create-cluster/nutanix.md
- docs/content/getting-started/deployment/_index.md
- docs/hugo.toml
- docs/layouts/shortcodes/param.html
- release-please-config.json
> docs: Add how to create clusters

- docs/go.mod
- docs/go.sum
- docs/layouts/_internal/google_analytics_async.html
Of course, the day after I apply a workaround to fix a hugo
incompatibility, docsy release a compatible module version...
This commit updates the docsy module and removes the workaround.
> docs: Update docsy module

- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/nutanix-cluster-class.yaml
- examples/capi-quick-start/nutanix-cluster-calico-crs.yaml
- examples/capi-quick-start/nutanix-cluster-calico-helm-addon.yaml
- examples/capi-quick-start/nutanix-cluster-cilium-crs.yaml
- examples/capi-quick-start/nutanix-cluster-cilium-helm-addon.yaml
- hack/examples/bases/nutanix/cluster/kustomization.yaml.tmpl
- hack/examples/bases/nutanix/clusterclass/kustomization.yaml.tmpl
Makes it easier for clients to consume the default ClusterClass templates and have consistent MD class names across providers.
Fixes #
> fix: use a consistent MachineDeployment class name

- api/v1alpha1/addon_types.go
- pkg/handlers/generic/lifecycle/serviceloadbalancer/handler.go
I noticed that the error handling was incorrect.
I also noticed that the field tag did not get updated in https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/issues/604, so I made that update here.
Fixes #
> fix: Do not return error if serviceLoadBalancer field is not set

- common/pkg/capi/utils/labels.go
- pkg/handlers/generic/mutation/imageregistries/credentials/credentials_secret.go
Moving the utility functions that creates labels to `common/utils` package.
I like to use these function in another mutator.
Existing unit tests
**Special notes for your reviewer:**
> refactor: move label helper functions to utils package

- common/pkg/k8s/client/apply.go
I noticed that the Patch options passed to the `ServerSideApply` helper functions were not used. 
As a result the `ForceOwnership` options from handlers such as https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/blob/main/pkg/handlers/generic/lifecycle/utils/secrets.go#L67 was ignored.
> fix: use provided options for serverside apply

- pkg/common/clusterconfig/types.go
Spotted in discussions with @dkoshkin about internal usage of types like
this as opposed to type switches.
> fix: Fix the internal ClusterConfig type used for provider-agnostic logic

- .golangci.yml
- test/e2e/e2e_suite_test.go
See https://github.com/golangci/golangci-lint/issues/4697 for details
and waiting on https://github.com/golangci/golangci-lint/pull/4698 to be
released before we can revert this fix.
> build: Temporary lint config fix until next golangci-lint release

- test/e2e/e2e_suite_test.go
- test/e2e/framework/provider_utils.go
- test/e2e/framework/self_hosted.go
In line with other provider types, this commit ensures a consistent version
is used for core, bootstrap, and control plane providers to ensure a repeatable
e2e test setup.
> test(e2e): Consistent core/bootstrap/control-plane provider versions

- .github/workflows/e2e.yml
Noticed `no space left on device` [error messages](https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/actions/runs/9008250141/job/24773942020?pr=638#step:5:276) in e2e tests which cases the tests to fail.
This PR runs a step to clean up the disk, replicated from upstream issue https://github.com/actions/runner-images/issues/2840
Fixes #
> ci: free up disk space before running tests

- test/helpers/envtest.go
Adds context to panic message:
**Before:**
```log
[PANICKED] Test Panicked
In [BeforeSuite] at: /home/dlipovetsky/nutanix/capi-runtime-extensions/test/helpers/envtest.go:205 @ 05/09/24 08:05:57.622
exit status 1
```
**After:**
```log
[PANICKED] Test Panicked
In [BeforeSuite] at: /home/dlipovetsky/nutanix/capi-runtime-extensions/test/helpers/envtest.go:205 @ 05/09/24 08:05:12.059
err="exit status 1", output="go: module sigs.k8s.io/cluster-api-provider-aws/v2: not a known dependency\n"
```
Fixes #
> test: Add more context to panic in envtest helper

- README.md
- devbox.json
- docs/content/getting-started/create-cluster/aws.md
- docs/content/getting-started/create-cluster/docker.md
- docs/content/getting-started/create-cluster/nutanix.md
- docs/hugo.toml
- make/all.mk
- make/docs.mk
- make/go.mk
- test/e2e/config/caren.yaml
Update documentation to specify the version when creating the cluster.
> build: Use k8s v1.29.4 as default Kubernetes version

- common/pkg/capi/clustertopology/handlers/mutation/meta.go
- hack/tools/helm-cm/main.go
- pkg/handlers/generic/lifecycle/ccm/aws/handler.go
- pkg/handlers/generic/lifecycle/ccm/nutanix/handler.go
- pkg/handlers/generic/lifecycle/utils/scs.go
- pkg/handlers/generic/lifecycle/utils/utils.go
- pkg/handlers/generic/mutation/controlplanevirtualip/providers/kubevip.go
The colon makes the overall message more readable.
**Before:**
```log
failed to fetch cluster no kind is registered for the type v1beta1.Cluster in scheme "pkg/runtime/scheme.go:100"
```
**After:**:
```log
failed to fetch cluster: no kind is registered for the type v1beta1.Cluster in scheme "pkg/runtime/scheme.go:100"
```
Fixes #
> refactor: Use colon to separate context from wrapped error

- common/pkg/capi/clustertopology/patches/generator.go
When a mutation fails the CAREN logs does not have any information. 
we have to refer to capi-controller's logs to see error returned by CAREN hooks. 
We should log mutation failure logs in CAREN.
By forcing an error and checking the logs.
```
E0510 02:17:47.751160       1 generator.go:65] "failed to apply mutation" err="forced logging of error" template="infrastructure.cluster.x-k8s.io/v1beta1/DockerMachineTemplate" holder="controlplane.cluster.x-k8s.io/v1beta1/KubeadmControlPlane/default/shalin-docker-jsbhl" holderRef={"apiVersion":"controlplane.cluster.x-k8s.io/v1beta1","kind":"KubeadmControlPlane","namespace":"default","name":"shalin-docker-jsbhl","fieldPath":"spec.machineTemplate.infrastructureRef"} …
```
> fix: log mutation failure errors

- make/apis.mk
- make/clusterctl.mk
- make/go.mk
- test/helpers/envtest.go
When GOWORK is enabled, "go list -m" always lists all modules in the workspace. To list the module for the current working directory, we disable GOWORK.
This is sound whether or not you use Go workspaces.
**Before**
```shell
> pwd
/capi-runtime-extensions/api
> go env GOWORK
/capi-runtime-extensions/go.work
> go list -m
github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix
github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/api
github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/common
github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/docs
github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/external/caaph …
```
> build: Make module-relative "go list -m" compatible with GOWORK

- pkg/common/containerd.go
- pkg/handlers/generic/mutation/containerdapplypatchesandrestart/apply_patches.go
- pkg/handlers/generic/mutation/containerdapplypatchesandrestart/inject_test.go
- pkg/handlers/generic/mutation/containerdapplypatchesandrestart/restart.go
- pkg/handlers/generic/mutation/containerdmetrics/metrics.go
- pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_install_files.go
- pkg/handlers/generic/mutation/imageregistries/credentials/inject_test.go
- pkg/handlers/generic/mutation/mirrors/inject_test.go
- pkg/handlers/generic/mutation/mirrors/mirror.go
- pkg/handlers/generic/mutation/mirrors/mirror_test.go
Previously, we wrote some configuration to /etc/cre. Now that the project name is CAREN, we should use /etc/caren.
We also wrote containerd configuration to /etc/containerd/cre.d, but this configuration is not read by containerd directly. Instead, it is read by a script that merges it to the primary containerd configuration. For that reason, this configuration belongs under /etc/caren.
Fixes #
> refactor: Write configuration under /etc/caren

- pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
- pkg/handlers/generic/mutation/imageregistries/credentials/inject_test.go
Makes the Cluster resource the owner of image registry credential Secret. CAREN creates this Secret for each Cluster, and it should be deleted when the Cluster is deleted. 
Fixes https://jira.nutanix.com/browse/D2IQ-100572
All test cases pass. The test is updated to create a Cluster resource, and to provide the handler a client that can read a Cluster resource.
> fix: Make Cluster the owner of image registry credential secret

- pkg/handlers/generic/mutation/containerdunprivilegedports/files/unprivileged-ports-config.toml
- pkg/handlers/generic/mutation/containerdunprivilegedports/inject.go
- pkg/handlers/generic/mutation/containerdunprivilegedports/inject_test.go
- pkg/handlers/generic/mutation/containerdunprivilegedports/unprivileged_ports.go
- pkg/handlers/generic/mutation/handlers.go
- test/e2e/config/caren.yaml
This enabled pods to run as non-root and bind to privileged ports
as long as they have the necessary capability, `CAP_NET_BIND_SERVICE`
added.
This fixes an issue on AWS when bringing up coredns which binds to port
53 but runs as an unprivileged user.
Overall this is a net security improvement for clusters, meaning users
can stop giving too many privileged to pods - see
https://github.com/kubernetes/kubernetes/issues/102612 for discussion.
Depends on #644.
> feat: Enable unprivileged ports sysctl in containerd config

- .goreleaser.yml
- docs/content/getting-started/deployment/via-helm.md
Instead of defaulting to a pretty long `cluster-api-runtime-extensions-nutanix-system` namespace, proposing to use a shorter name. This is similar to other CAPI providers:
```
$ kubectl get providers -A
NAMESPACE                                       NAME                            AGE   TYPE                       PROVIDER         VERSION
caaph-system                                    addon-helm                      91s   AddonProvider              helm             v0.2.1
capa-system                                     infrastructure-aws              95s   InfrastructureProvider     aws              v2.3.5
capg-system                                     infrastructure-gcp              92s   InfrastructureProvider     gcp              v1.5.0 …
```
> build: us a shorter namespace caren-system

- test/e2e/ownerreference_helpers.go
This commit copies the upstream check by allowing `KubeadmControlPlane` and
`KubeadmConfig` owners, but adds `Cluster` as well as the secrets that CAREN
generates are owned by the relevant `Cluster` to ensure they are cleaned up
as part of Kubernetes resource garbage collection following deletion of the
`Cluster`.
> test(e2e): Fix up secret ownership checks

- test/e2e/e2e_suite_test.go
Removes hard-coded text focus and label for e2e tests.
This code took precedent over any configuration provided to ginkgo at
runtime, so only single e2e test matching both focus and labels could
run.
Fixes #
I used dry-run (added in #666) to confirm that the removed code was the root cause.
> test: Remove hard-coded text focus and label for e2e tests

- make/go.mk
- Use Ginkgo dry-run mode to debug e2e test selection logic
- Verbosity is enabled in CI, and dry-run mode
I'm using this to debug an issue with e2e tests.
<details>
<summary>Example output</summary>
<code>
> make e2e-test E2E_LABEL='provider:Nutanix && cni:Cilium && addonStrategy:HelmAddon' E2E_DRYRUN=true
▶ dry-running e2e tests labelled "provider:Nutanix && cni:Cilium && addonStrategy:HelmAddon"
make[1]: Entering directory '/home/dlipovetsky/nutanix/capi-runtime-extensions'
▶ running go generate
▶ building snapshot release
...
Will run 1 of 16 specs
------------------------------
[SynchronizedBeforeSuite]
/home/dlipovetsky/nutanix/capi-runtime-extensions/test/e2e/e2e_suite_test.go:87
[SynchronizedBeforeSuite] PASSED [0.000 seconds] …
> test: Add E2E_DRYRUN and E2E_VERBOSE make vars

- charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/aws/crs-installation.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/aws/helm-addon-installation.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/docker/crs-installation.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/docker/helm-addon-installation.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/nutanix/crs-installation.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/nutanix/helm-addon-installation.yaml
This reduces need for Docker Hub credentials by pulling images from
another registry that has Calico images pushed to on new Calico
releases.
> feat: Pull calico images from quay.io instead of docker hub

- pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files_test.go
- pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_install_files.go
- pkg/handlers/generic/mutation/imageregistries/credentials/templates/dynamic-credential-provider-config.yaml.gotmpl
Fixes falling back to origin registry if mirror does not contain
requested image.
> fix: Upgrade dynamic-credential-provider to v0.5.3

- make/go.mk
The existing `if` condition will always evaluate to true because it is
checking if `E2E_DRYRUN` has _any_ content. Change this to check that
`E2E_DRYRUN` is set to `true` before outputting `dry-` in this place.
This is already done correctly in other places, so just tidying up a
typo from earlier PR.
> build: Correct dry-run output

- docs/content/getting-started/deployment/via-clusterctl.md
- docs/content/getting-started/deployment/via-helm.md
> docs: Add released version to helm and clusterctl install

- pkg/handlers/generic/lifecycle/ccm/handler.go
- pkg/handlers/generic/lifecycle/clusterautoscaler/handler.go
- pkg/handlers/generic/lifecycle/cni/calico/handler.go
- pkg/handlers/generic/lifecycle/cni/calico/strategy_crs.go
- pkg/handlers/generic/lifecycle/cni/cilium/handler.go
- pkg/handlers/generic/lifecycle/csi/handler.go
- pkg/handlers/generic/lifecycle/nfd/handler.go
- pkg/handlers/generic/lifecycle/serviceloadbalancer/handler.go
This should reduce noise in logs.
> refactor: Reduce log verbosity for skipped handlers

- hack/addons/configure-supported-csi-providers.sh
- make/addons.mk
- make/dev.mk
- make/go.mk
PR #695 was merged before I pushed the refactoring to move the logic into a script - this commit contains those changes.
Fixes #
> build: Move CSI supported provider logic to script

- pkg/handlers/generic/mutation/imageregistries/credentials/credentials_secret.go
- pkg/handlers/generic/mutation/imageregistries/credentials/inject_test.go
Wanted to avoid "creds" abbreviation.
Also, the Konvoy secret names are `<cluster-name>-image-registry-credentials` and `<cluster-name>-image-registry-mirror-credentials` so it was pretty confusing also having a `<cluster-name>-registry-creds`. Wanted to make it a little more descriptive. (Suggestions welcome!)
Here is what that Secret looks like:
```
{
"kind":"CredentialProviderResponse",
"apiVersion":"credentialprovider.kubelet.k8s.io/v1",
"cacheKeyType":"Image",
"cacheDuration":"0s",
"auth":{
"docker.io": {"username": "<>", "password": "<>"}
}
}
```
Fixes #
> refactor: rename credential provider response secret

- pkg/handlers/generic/lifecycle/ccm/nutanix/handler.go
- pkg/handlers/generic/lifecycle/csi/nutanix-csi/handler.go
- pkg/handlers/generic/lifecycle/utils/secrets.go
- pkg/handlers/generic/lifecycle/utils/secrets_test.go
Add `ownerRef` to Nutanix CSI Secret with the corresponding Cluster.
CAPX already adds an ownerRef to the PC credentials Secret that CAPX uses so did not add it there.
Fixes https://jira.nutanix.com/browse/NCN-100575
> fix: nutanix credentials Secrets owner refs

- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/nutanix-cluster-class.yaml
- hack/examples/bases/nutanix/clusterclass/kustomization.yaml.tmpl
- pkg/handlers/generic/mutation/controlplanevirtualip/inject.go
- pkg/handlers/generic/mutation/controlplanevirtualip/inject_test.go
- pkg/handlers/generic/mutation/controlplanevirtualip/providers/kubevip.go
- pkg/handlers/generic/mutation/controlplanevirtualip/providers/kubevip_test.go
- pkg/handlers/generic/mutation/controlplanevirtualip/providers/providers.go
- pkg/handlers/generic/mutation/controlplanevirtualip/providers/templates/configure-for-kube-vip.sh
- pkg/handlers/generic/mutation/controlplanevirtualip/providers/templates/configure-kube-vip.sh
- pkg/handlers/generic/mutation/encryptionatrest/inject.go
This PR refactors the kube-vip handler to:
1. Use a script file when running preKubeadmCommands/postKubeadmCommands. IMO this is simpler to maintain and change in the future instead of looking for complex multi-line strings in the slices.
2. Move `echo "127.0.0.1   kubernetes" >>/etc/hosts` out of the template and into the handler since this command is not unique to Nutanix and would be needed for other infra providers using kube-vip.
Fixes #
> refactor: kube-vip commands

- pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
Saw that the owner was not getting correctly set on image credential Secret.
Fixes #
> fix: credential provider response secret ownership

- make/goreleaser.mk
The make variable reference was replaced recently in https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/704/files#diff-fa98b7f1d4a049ad777fb9453f6657c512c8b715a9f8bc47dfd57f1143bbb930L14.
The new reference is to `GORELEASE_VERBOSE`, which is unset, and goreleaser fails:
```shell
> make build-snapshot
▶ running go generate
make[1]: Entering directory '/home/dlipovetsky/nutanix/capi-runtime-extensions'
▶ configuring supported csi providers
make[1]: Leaving directory '/home/dlipovetsky/nutanix/capi-runtime-extensions'
▶ building snapshot
⨯ command failed                                   error=invalid argument "" for "--verbose" flag: strconv.ParseBool: parsing "": invalid syntax
```
Not sure how CI passed for #704, …
> build: Fix an incorrect make variable passed to goreleaser

- hack/third-party/caaph/go.mod
- hack/third-party/caaph/go.sum
Upgrade CAAPH to 0.2.4
This release includes fixes needed for supporting CAAPH in airgap environment.
🌱 Use upstream cluster RESTConfig utility by @jimmidyson in https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/pull/248
🐛 Fix OCI client configuration logic by @jimmidyson in https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/pull/252
🐛 pointer checks if user doesn't specify CASecret by @faiq in https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/pull/253
Fixes #
> feat: bumps caaph to 0.2.4

- charts/cluster-api-runtime-extensions-nutanix/templates/csi/nutanix/manifests/helm-addon-installation.yaml
With this change, all Nutanix CSI components can run on a single node cluster.
Fixes #https://jira.nutanix.com/browse/NCN-100706
> fix: Allow Nutanix CSI snapshot controller & webhook to run on CP nodes

- pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files.go
- pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files_test.go
- pkg/handlers/generic/mutation/imageregistries/credentials/templates/kubelet-image-credential-provider-config.yaml.gotmpl
While debugging another issue where I launched a local registry in a container at `https://172.18.0.10:5000`, I noticed that Deployments with an image in that registry failed:
```
Warning  Failed     7m14s (x4 over 8m47s)   kubelet            Failed to pull image "172.18.0.10:5000/library/nginx:latest": failed to pull and unpack image "172.18.0.10:5000/library/nginx:latest": failed to resolve reference "172.18.0.10:5000/library/nginx:latest": pull access denied, repository does not exist or may require authorization: authorization failed: no basic auth credentials
```
This is because of a bug in how `matchImages` in `CredentialProviderConfig` was generated, the globs don't match images with a port or a path. This PR fixes that by explicitly including …
> fix: CredentialProviderConfig matchImages to support registries with port

- .pre-commit-config.yaml
- make/helm.mk
Previously, the chart docs could only be updated by running pre-commit. Now they can be updated by running `make chart-docs`. (Pre-commit now uses this make target as well).
Fixes #
> build: Add 'chart-docs' make target

- charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/helm-addon-installation.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/node-feature-discovery-configmap.yaml
- hack/addons/kustomize/nfd/helm-values.yaml
With this change, all NFD components can run on a single node cluster.
Fixes #https://jira.nutanix.com/browse/NCN-100706
> fix: Allow Node Feature Discovery garbage collector to run on control-plane nodes

- .github/workflows/checks.yml
- .github/workflows/e2e.yml
- .github/workflows/release-tag.yml
- .goreleaser.yml
- hack/addons/mindthegap-helm-registry/Dockerfile
This commit makes the CAREN mindthegap registry image a multiarch
image by building both amd64 and arm64 variants and pushing a
docker multiarch image manifest to the target registry.
> build: Make CAREN mindthegap reg multiarch

- .github/workflows/checks.yml
- .github/workflows/e2e.yml
- .github/workflows/release-tag.yml
- .goreleaser.yml
- make/goreleaser.mk
This should fix the local development flow for `make release-snapshot`.
Tested on amd64 and arm64.
We also remove unnecessary use of third-party github actions for docker
We now have a make target that creates a dockerx builder container
with multiarch support. Both the release and release-snapshot make
targets depend on this make target.
The two github actions are no longer necessary, and are removed.
Fixes #
> fix: adds a docker buildx step before release-snapshot

- api/v1alpha1/constants.go
- charts/cluster-api-runtime-extensions-nutanix/README.md
- charts/cluster-api-runtime-extensions-nutanix/templates/deployment.yaml
- charts/cluster-api-runtime-extensions-nutanix/values.schema.json
- charts/cluster-api-runtime-extensions-nutanix/values.yaml
- cmd/main.go
- pkg/controllers/namespacesync/flags.go
- Allows user to configure target namespace label key using flag. Sets the default label key as an empty string. Labels cannot have an empty key, which means that, by default, no namespaces are target namespaces.
- Adds configuration fields to helm values, and passes them to manager as flags. Defines `caren.nutanix.com/namespace-sync` as the default target namespace label key.
- Documents configuration fields and their default values.
#725 fixes behavior when the source namespace and/or target namespace label key are empty strings.
Fixes #
I think this behavior deserves to be documented, but right now the only place where we talk about configuration …
> feat: Configure namespace sync in helm chart

- pkg/controllers/namespacesync/controller.go
- pkg/controllers/namespacesync/controller_test.go
- pkg/controllers/namespacesync/label.go
- pkg/controllers/namespacesync/label_test.go
Previously, the controller listed resources in all namespaces when the source namespace was an empty string. Now, it lists no resources.
The PR adds a test verifying the above. It also adds a test that verifies that an the controller will not match any namespaces when the target namespace label key is an empty string. 
Fixes #
> fix: Namespace Sync controller should list no resources when source namespace is empty string

- test/e2e/config/caren.yaml
When running e2e tests for other providers, it is currently necessary
to export empty variables for `NUTANIX_ENDPOINT`, `NUTANIX_PASSWORD`
and `NUTANIX_USER`. This commit sets these to empty values in the
e2e configuration so they are not required for other providers e2e
tests but can still be overridden when running the Nutanix e2e tests.
> test(e2e): Set empty env vars for Nutanix e2e vars

- charts/cluster-api-runtime-extensions-nutanix/templates/csi/nutanix/manifests/helm-addon-installation.yaml
Necessary until this is fixed in GA Nutanix CSI 3.0 release.
CSI pods come up testing against Sherlock!
```
ntnx-system              nutanix-csi-controller-574bdd7b96-4v9fs               7/7     Running             0  4m22s
ntnx-system              nutanix-csi-controller-574bdd7b96-nd8r6               7/7     Running             0  4m22s
ntnx-system              nutanix-csi-node-n5sfx                                3/3     Running             0  2m1s
ntnx-system              nutanix-csi-node-plx8l                                3/3     Running             0  3m31s
```
> fix: Temporarily hard-code supported PC version for Nutanix CSI

- pkg/handlers/generic/mutation/mirrors/containerd_files.go
- pkg/handlers/generic/mutation/mirrors/inject.go
- pkg/handlers/generic/mutation/mirrors/inject_test.go
Found a bug when testing with a mirror registry where it doesn't have the CA key set in the Secret.
The handler incorrectly generated a patch to add `/etc/certs/...` file with a Secret source and key `ca.crt`, however its possible that the Secret does not have that key set.
Example of an incorrect file:
```
- contentFrom:
secret:
key: ca.crt
name: e2e-aws-ag-cc-test-1719374309-image-registry-mirror-credentials
path: /etc/certs/999867407951.dkr.ecr.us-west-2.amazonaws.com-e2e-aws-ag-cc-test-1719374309.pem
permissions: "0600"
```
This led to CAPI failing because `ca.crt` did not exist in the Secret.
Fixes #
The first commit contains a failing unit tests to cover this scenario.
**Special …
> fix: skip kubeadm CA file when Secret doesn't have a CA 

- pkg/handlers/generic/lifecycle/serviceloadbalancer/handler.go
- pkg/handlers/generic/lifecycle/serviceloadbalancer/handler_test.go
I found a bug while working on SLB configuration (future PR). Wrote a failing test, and fixed the bug.
Fixes #
> fix: Correctly report failed deploy of ServiceLoadBalancer

- test/e2e/ccm_helpers.go
- test/e2e/csi_helpers.go
This was missed in previous PR, but discovered by manually running
AWS e2e test suite.
> test(e2e): Correct default helm release names for AWS CCM and EBS CSI

- .goreleaser.yml
In v0.11.0 release we discovered that the "v" was unintentionally dropped [in this PR](https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/745/files). Bringing it back.
Fixes #
> build: bring back v prefix in releases

- examples/capi-quick-start/nutanix-cluster-calico-crs.yaml
- examples/capi-quick-start/nutanix-cluster-calico-helm-addon.yaml
- examples/capi-quick-start/nutanix-cluster-cilium-crs.yaml
- examples/capi-quick-start/nutanix-cluster-cilium-helm-addon.yaml
- hack/addons/kustomize/nutanix-ccm/kustomization.yaml.tmpl
- hack/examples/patches/nutanix/ccm.yaml
- test/e2e/ccm_helpers.go
Missed in previous PR when this ws refactored for AWS CCM. This
was not found in the PR checks because we still do not have CI
running on Nutanix infrastructure - but that is coming soon!
I have tested this manually by running e2e against sherlock dev.
> fix: Add strategy to Nutanix CCM addon in examples

- .github/workflows/checks.yml
- .github/workflows/e2e.yml
- .github/workflows/github-pages.yml
- make/dev.mk
- make/goreleaser.mk
Piping from and to devbox commands leads to errors like `Text
file busy` or `No file found` as they attempt to write their
respective commands to temporary files. Moving these to devbox
scripts should fix this and bring CI back to stable.
> build: Fix devbox run errors due to piped commands

- .github/workflows/checks.yml
- charts/cluster-api-runtime-extensions-nutanix/README.md
- charts/cluster-api-runtime-extensions-nutanix/README.md.gotmpl
Broken in previous update by not setting the `KUBECONFIG`
correctly.
Also update the date in chart README to trigger the ct
workflow which only runs when the chart is updated to
ensure this is actually fixed.
> ci: Fix ct check

- pkg/controllers/namespacesync/copy.go
Objects are garbage-collected if owners are not in the target namespace.
Unfortunately, the envtest-based integration tests missed this, because envtest does not have garbage collection.
I'd like an e2e test to create a cluster in a separate namespace, but that might in a future PR.
Fixes #
> fix: Copy ClusterClasses and Templates without their owner references

- cmd/main.go
- pkg/controllers/namespacesync/controller.go
- pkg/controllers/namespacesync/controller_test.go
- pkg/controllers/namespacesync/suite_test.go
The namespacesync controller did not reconcile a namespace when it was updated. We anticipated namespaces to meet the criteria for "target namespace" when they were created. We also wanted to avoid reconciling namespaces unnecessarily.
This PR makes the controller reconcile an updated namespace, if the answer to question "is this a target namespace," has changed. It also adds an integration test (which fails without the subsequent fix commit).
Fixes #
> fix: Namespacesync controller should reconcile an updated namespace

- pkg/wait/wait.go
- pkg/wait/wait_test.go
Implements a wait for a check to pass against a typed object.
We'll use this in some lifecycle handers, e.g., in a future change for deploying ServiceLoadBalancer configuration to the remote cluster.
(This is a copy of #762. I had to close that after #755 added required checks that can't be run from PRs from public forks. )
Fixes #
> feat: Add waiter for object 

- charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/helm-addon-installation.yaml
When deploying with the helm addon strategy i noticed that we did not deploy the minimal image. 
I'm going to follow this up with a PR that automates syncing the values in the templates and `hack/addons/kustomize/**/helm-values.yaml` 
Fixes #
> fix: use minimal image when deploying nfd chart

- test/e2e/config/caren.yaml
Avoids image pull rate limiting as images are published to ghcr.io.
> test(e2e): Use mesosphere fork v1.7.3-d2iq.1 for CAPI providers

- pkg/handlers/generic/lifecycle/serviceloadbalancer/handler.go
- pkg/handlers/generic/lifecycle/serviceloadbalancer/handler_test.go
- pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/configuration.go
- pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
- Generates MetalLB configuration from ServiceLoadBalancer Configuration API (added in #778)
- Waits for MetalLB helm chart to be successfully deployed (using waiter added in #777)
- Applies MetalLB configuration to remote cluster, also using a wait.
To apply MetalLB configuration, the MetalLB CRD webhooks must be ready. This is not guaranteed to happen once the MetalLB helm chart is successfully deployed.
Because the MetalLB configuration is applied in a non-blocking lifecycle hook, the topology controller retries the hook immediately after it returns; we cannot ask for a delay. Because the topology controller backs off its requests exponentially, this often results in the hook requests being delayed for 3+ minutes before succeeding. 
To mitigate …
> feat: Apply MetalLB configuration to remote cluster

- .github/workflows/e2e.yml
In an attempt to speed up Nutanix e2e tests.
> ci: Disable nix cache on self-hosted runners

- pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/configuration.go
- pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
The ServiceLoadBalancer configuration is optional; when it is not set, we should not configure the provider.
Thanks to @dkoshkin for finding this bug.
The e2e tests in #788 did not catch this, because they do define configuration.
Fixes #
> fix: Only create MetalLB configuration when necessary

- .github/workflows/checks.yml
It's wasteful to run the e2e jobs before the other jobs pass, since making the other jobs pass almost certainly requires a change to the PR, which then requires the e2e jobs to run again, discarding the previous result.
Before:
After:
Fixes #
> ci: Run e2e jobs only if unit-test, lint-*, and pre-commit jobs pass

- .github/workflows/e2e.yml
- make/go.mk
- Use the E2E_VERBOSE make variable to enable verbose output.
- Remove the CI make variable, because we never used it.
Fixes #
> ci: Enable verbose output for e2e tests

- pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
- pkg/handlers/utils/utils.go
This commit removes the `pod-security.kubernetes.io/audit` and
`pod-security.kubernetes.io/warn` labels as they are redundant when
specifying the `pod-security.kubernetes.io/enforce` label to the same
level.
Also add the `pod-security.kubernetes.io/enforce-version` label to
always enforce the latest pod security policy version, even on upgrade.
This is fine because we are specifying the most privileged pod security
standard, `privileged`, and as such should be safe to always enforce the
latest policy version.
> fix: Clean up MetalLB pod security standards labels

- pkg/handlers/generic/mutation/etcd/inject.go
- pkg/handlers/generic/mutation/etcd/inject_test.go
This increases ootb security and provides STIG compliance for
this area at least.
Fixes #806.
> feat: Secure ciphers, min TLS v1.2, and disable auto TLS for etcd

- .github/workflows/e2e.yml
- README.md
- make/go.mk
- test/e2e/config/caren.yaml
- test/e2e/e2e_suite_test.go
> feat: Bump default k8s version for tests to v1.29.6

- pkg/handlers/generic/lifecycle/ccm/aws/strategy_crs.go
- pkg/handlers/generic/lifecycle/clusterautoscaler/handler.go
- pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_crs.go
- pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_helmaddon.go
- pkg/handlers/generic/lifecycle/cni/calico/strategy_crs.go
- pkg/handlers/generic/lifecycle/cni/cilium/strategy_crs.go
- pkg/handlers/generic/lifecycle/csi/awsebs/strategy_crs.go
- pkg/handlers/generic/lifecycle/csi/localpath/strategy_crs.go
- pkg/handlers/generic/lifecycle/csi/snapshotcontroller/strategy_crs.go
- pkg/handlers/generic/lifecycle/nfd/strategy_crs.go
- pkg/handlers/utils/utils.go
- test/e2e/ownerreference_helpers.go
- test/e2e/quick_start_test.go
The Cluster Autoscaler addon (either HelmChartProxy or ClusterResourceSet
) has to be deployed in the management cluster namespace and as such cannot
be owned by the workload cluster, which commonly resides in a different
namespace.
This commit fixes that and introduces a BeforeClusterDelete hook to delete
the HelmChartProxy or ClusterResourceSet rather than relying no Kubernetes
GC as was previously expected.
Tested locally. Created workload cluster in different namespace to management cluster. HCP does not have ownership set:
```
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
creationTimestamp: "2024-07-18T13:02:30Z"
finalizers:
- helmchartproxy.addons.cluster.x-k8s.io
generation: 1
name: cluster-autoscaler-my-docker-cluster
namespace: test
resourceVersion: …
```
> fix: Fix ownership of ClusterAutoscaler resources

- charts/cluster-api-runtime-extensions-nutanix/templates/csi/nutanix/manifests/helm-addon-installation.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
- hack/addons/kustomize/nutanix-storage-csi/kustomization.yaml.tmpl
- hack/addons/mindthegap-helm-registry/repos.yaml
- make/addons.mk
This version fixes a race condition when creating multiple PVs.
https://github.com/nutanix-scratch/helm/releases/tag/nutanix-csi-storage-3.0.0-2458
Tested
```
kubectl get deploy -n ntnx-system -o yaml | grep "image: docker.io/nutanix/ntnx-csi"
image: docker.io/nutanix/ntnx-csi:3.0.0-2458
```
```
kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                                    STORAGECLASS     VOLUMEATTRIBUTESCLASS   REASON   AGE
pvc-d13bf2f8-644d-424b-a347-811a78bdd11b   10Gi       RWO            Delete           Bound    e2e-volume-pvc-bound-to-pv/pv-volume-volume-pvc-bound-to-pv-tester-2-0   nutanix-volume   <unset>                          8m36s …
```
> fix: category race condition by updating Nutanix CSI to 3.0.0-2458

- charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
- hack/addons/kustomize/nutanix-storage-csi/kustomization.yaml.tmpl
- hack/addons/mindthegap-helm-registry/repos.yaml
The GA version of the Nutanix CSI was just released, using the production repo.
Tested locally:
```
k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                                  STORAGECLASS     VOLUMEATTRIBUTESCLASS   REASON   AGE
pvc-d5fc542d-0cb8-4051-bc5a-334fc22693b8   10Gi       RWO            Delete           Bound    e2e-volume-pvc-bound-to-pv/pv-volume-volume-pvc-bound-to-pv-tester-0   nutanix-volume   <unset>                          28s
```
And a PV with a hypervisor attached volume:
```
k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM …
```
> fix: use production repo for Nutanix CSI to 3.0.0-2458

- charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
- hack/addons/mindthegap-helm-registry/repos.yaml
- make/addons.mk
> fix: Use correct GA Nutanix CSI version

- api/v1alpha1/http_proxy.go
- api/v1alpha1/http_proxy_test.go
FluxCD uses this configuration as a default domain for controllers communication.
https://github.com/fluxcd/flux2/blob/main/manifests/bases/helm-controller/patch.yaml#L1-L3
https://github.com/fluxcd/flux2/blob/main/manifests/bases/source-controller/patch.yaml#L1-L3
> fix: add cluster domain with final dot to no proxy list

- .goreleaser.yml
- make/dev.mk
- make/go.mk
- test/e2e/config/caren.yaml
Previous builds were overriding the `GOOS` and `GOARCH` enviroment
variables, which is fine to do when using `ko` directly, but appears to be
broken when building via ko using `goreleaser`.
This commit ensures that `GOOS` and `GOARCH` are always unset when
running builds by undefining them via `make` `undefine`. The `override`
keyword ensures that the env vars are always undefined regardless of the
source (e.g. enviroment, make variables, etc) to ensure a clean build
environment.
Instead of using `GOARCH` env var for building for the local build
architecure, this commit uses `goreleaser`'s `{{ .Runtime.Goarch }}`
variable available via templating which contains the architecture of the
build machine.
This commit also removes the `ldflags` config from the `ko`
configuration in `goreleaser` …
> build: Ensure clean go build environment for goreleaser and ko

- make/dev.mk
By switching the way that make assigns variables, the shell calls to
determine the snapshot image version will only be called when necessary,
rather than when parsing the Makefile. This cleans up noisy build messages,
which do not break the build but are noisy.
> build: Remove noisy build messages

- pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_crs.go
- pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_helmaddon.go
- pkg/handlers/utils/utils.go
This commit changes ownership of the CA addon to be owned by the
management cluster (either the bootstrap cluster or the managemen
cluster) which fixes moving the resources only after the cluster
exists on the target cluster.
> fix: ClusterAutoscaler addon ownership for move

- make/repo.mk
Using directory path previously was fragile dependent on where the repo was
cloned to locally.
> build: Derive GH owner/repo via gh

- pkg/handlers/generic/mutation/containerdapplypatchesandrestart/templates/containerd-restart.sh
During Machine bootstrapping Contianerd drop in files may be added. 
These files are written to the disk before `preKubeadmCommmands` are run. 
Always run systemctl daemon-reload along with systemctl restart containerd to pick up these dropins.
I saw a warning about the drop-ins when cloud init runs the Containerd restart script, so figured it makes sense to add it here instead of a separate script.
```
[2024-08-05 16:35:46] /tmp/tmp.MzIe5jTIdG
[2024-08-05 16:35:46] Warning: The unit file, source configuration file or drop-ins of containerd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
[2024-08-05 16:35:46] /usr/bin/crictl
[2024-08-05 16:35:46] {
...
```
Fixes # …
> fix: run systemctl daemon-reload before Containerd restart

- common/go.mod
- common/pkg/capi/clustertopology/handlers/lifecycle/interfaces.go
- common/pkg/capi/clustertopology/handlers/lifecycle/ordered.go
- pkg/handlers/generic/lifecycle/handlers.go
- pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
This commit introduces wrapper handlers to allow ordering
of lifecyce hooks to be called via a single registered hook.
This ensures that hooks are called in a defined order, fixing
issues that have arisen that require CNI hook to be applied
before metallb hook.
> fix: Deterministic ordering of lifecycle hooks

- pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_helmaddon.go
The HCP will always be deployed in the management cluster's namespace.
Fixes #
> fix: delete correct cluster-autoscaler HCP

- docs/content/contributing/releasing.md
> docs: Update release process for adding release series metadata

- internal/test/envtest/environment.go
- pkg/webhook/cluster/clusteruuidlabeler.go
- pkg/webhook/cluster/webhook_suite_test.go
- pkg/webhook/cluster/webhook_test.go
We only want this webhook to run on Clusters that are created with cluster topology. This also fixes an issue when an existing Cluster that was created before deploying CAREN and this webhook is moved to the bootstrap cluster.
Currently it fails the move with 
```
2024-08-14 11:14:55 ERR     err="unable to pivot to the to-cluster: error setting Cluster.Spec.Paused=true: action failed after 10 attempts: error patching Cluster default/e2e-preprovisioned-upgrade-573225644: admission webhook "cluster-validator.caren.nutanix.com" denied the request: missing cluster UUID annotation caren.nutanix.com/cluster-uuid"
```
Fixes #
I'm also now wondering if we …
> fix: skip UUID annotation webhook for clusters with nil topology

- charts/cluster-api-runtime-extensions-nutanix/templates/cluster-autoscaler/manifests/cluster-autoscaler-configmap.yaml
- hack/addons/update-cluster-autoscaler.sh
- test/e2e/clusterautoscaler_helpers.go
- test/e2e/configmap_helpers.go
Fixes an issue with CRS genertated CA Deployment not working because of extra quotes.
```
I0815 20:12:58.376871       1 reflector.go:332] Listing and watching cluster.x-k8s.io/v1beta1, Resource=machines from k8s.io/client-go/dynamic/dynamicinformer/informer.go:108
W0815 20:12:58.379140       1 reflector.go:547] k8s.io/client-go/dynamic/dynamicinformer/informer.go:108: failed to list cluster.x-k8s.io/v1beta1, Resource=machines: machines.cluster.x-k8s.io is forbidden: User "system:serviceaccount:default:cluster-autoscaler-0191579a-2104-7ace-a5a2-ceae4590d7fe" cannot list resource "machines" in API group "cluster.x-k8s.io" in the namespace "'default'"
E0815 20:12:58.379170       1 reflector.go:150] …
```
> fix: CRS generated CA Deployment has extra quotes

- charts/cluster-api-runtime-extensions-nutanix/templates/helm-repository.yaml
The helm-repository should be a system critical pod as if it is unavaialable
then no clusters will be creatable.
> fix: Use same security context & priority class for helm-repository pod

- .goreleaser.yml
Allows the user of a release image to set breakpoints and tracepoints.
Size of executable increases from 47MB to 65MB, or approximately 38 percent.
Fixes #
> build: Include debug symbols in release image executable

- .github/workflows/release-please.yml
Required to continue iterating on CAREN while creating backports
for previous versions as required.
> ci: Support release branches for release-please

- .goreleaser.yml
Prevents confusion over what version is being built locally.
> build: Update patch only for local release branch dev builds

- .github/workflows/release-please.yml
Correctly run release-please in context of release branch.
Already present in main, duplicating to release branch.
> ci: Fix up release please trigger for release branches

- charts/cluster-api-runtime-extensions-nutanix/README.md
- charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.27.9-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.28.9-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.29.6-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.30.2-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.31.0-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/helm-addon-installation.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/csi/aws-ebs/manifests/aws-ebs-csi-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/csi/aws-ebs/manifests/helm-addon-installation.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/csi/local-path/manifests/helm-addon-installation.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/csi/local-path/manifests/local-path-provisioner-csi-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/csi/nutanix/manifests/helm-addon-installation.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/csi/snapshot-controller/manifests/helm-addon-installation.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/helm-addon-installation.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/node-feature-discovery-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/values.yaml
- hack/addons/kustomize/aws-ccm/helm-values.yaml
- hack/addons/kustomize/aws-ebs-csi/helm-values.yaml
- hack/addons/kustomize/local-path-provisioner-csi/helm-values.yaml
- hack/addons/kustomize/nfd/helm-values.yaml
- pkg/handlers/generic/lifecycle/ccm/aws/handler_test.go
This was removed in Kubernetes v1.24 so is no longer needed and actually
throws a warning now if it is kept when applying manifests:
```
[KubeAPIWarningLogger] spec.template.spec.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[1].preference.matchExpressions[0].key: node-role.kubernetes.io/master is use "node-role.kubernetes.io/control-plane" instead
```
Removal note in https://kubernetes.io/blog/2022/04/07/upcoming-changes-in-kubernetes-1-24/#api-removals-deprecations-and-other-changes-for-kubernetes-1-24.
Blocked by #893.
> fix: Remove deprecated toleration for node-role.kubernetes.io/master

- charts/cluster-api-runtime-extensions-nutanix/templates/cni/cilium/manifests/helm-addon-installation.yaml
- hack/addons/kustomize/cilium/helm-values.yaml
- pkg/handlers/generic/lifecycle/ccm/aws/handler.go
- pkg/handlers/generic/lifecycle/ccm/nutanix/handler.go
- pkg/handlers/generic/lifecycle/cni/cilium/handler.go
- pkg/handlers/generic/lifecycle/csi/awsebs/handler.go
- pkg/handlers/generic/lifecycle/csi/localpath/handler.go
- pkg/handlers/generic/lifecycle/csi/snapshotcontroller/handler.go
- test/e2e/clusterautoscaler_helpers.go
- test/e2e/cni_helpers.go
- test/e2e/framework/self_hosted.go
Relay is required for network visibility of a cluster as a whole. See https://docs.cilium.io/en/stable/gettingstarted/hubble_intro/.
Fixes #
> feat: Enable Hubble Relay in Cilium deployment via CAAPH

- .goreleaser.yml
- hack/tools/fetch-images/main.go
- make/addons.mk
Calico images are deployed by the tigera-operator and as such are not
discoverable by the helm list images plugin. Using the extra images file
functionality of the helm list images plugin allows for adding these
images as templated strings that will adapt with the chart version as it
is updated in future.
This commit also fixes up some other things:
- Use `filepath` instead of `path` for portabiity
- Output the image list to stdout from make to allow user to decide
where to redirect list to
- Omit changing dir from image list when running as goreleaser hook
- Slightly more defensive when checking errors
Final output is:
```shell
$ make list-images
docker.io/nutanix/ntnx-csi-precheck:3.0.0
docker.io/nutanix/ntnx-csi:3.0.0
docker.io/rancher/local-path-provisioner:v0.0.28 …
```
> build: Include Calico images in image list

- docs/content/contributing/releasing.md
- make/dev.mk
- test/e2e/config/caren.yaml
- enable creating release-please PR from release branch
- set caren provider to use v0.15.x in CAREN e2e tests.
> ci(main): enable creating release-please PR from release branches

- docs/content/contributing/releasing.md
- make/dev.mk
- test/e2e/config/caren.yaml
- enable creating first release-please PR for release branches
- change CAREN e2e config to use version 0.14.x
on branches other than `main` and `release/*`
```
make release-please
make/dev.mk:49: *** "release-please should only be run on the main or release branch".  Stop.
```
on `release/v0.1.4.x` branch
https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/910
> ci(release/v0.14.x): enable creating release-please PR from release branches

- metadata.yaml
- test/e2e/config/caren.yaml
- test/e2e/data/shared/v1beta1-caren/metadata.yaml
Metadata files were not correctly updated at time of release so fixing
up here.
> build: Fix up metadata missed in v0.16.0 release process

- .pre-commit-config.yaml
- make/go.mk
- make/make.mk
Reworked checks in pre-commit config to check if generated files are
consistent after running `make go-generate`, which is called when
building the release so we are confident this doesn't get broken in any
future PRs.
Calling golines when generating deepcopy, etc will ensure a consistent
formatting for these generated files.
Also reinstated go fix as this is now properly supported in recent go versions.
And finally simplify the ignore external call by using golines flag rather than
a grep on the go source dirs.
> build: Consistently format even generated files

- cmd/main.go
- pkg/features/feature_gates.go
This will be used by upcoming experimental features such as in-cluster registry. Just adding the plumbing for now.
Fixes #
> feat: Add feature-gates plumbing

- charts/cluster-api-runtime-extensions-nutanix/templates/deployment.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/helm-repository.yaml
Default readiness probe period is 10s so this should reduce timeouts
caused by overzealous probes.
This will need to backported to 0.14 release branch.
> fix: Shorten readiness probe period to try to prevent races

- make/goreleaser.mk
Current config only allows building local binaries on Linux machines so
adding config to allow building binaries on macos without changing the
release config (and hence still only releasing linux binaries as required).
> build: Enable building binary only on macos

- charts/cluster-api-runtime-extensions-nutanix/templates/deployment.yaml
The clusterctl logic to wait for providers to be ready depends on the
container name being manager (see
https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/internal/util/objs.go#L181)
otherwise it will not wait for the provider to be ready and hence
potentially
return too early for other client operations.
Backport of #932.
> fix: [release/v0.14.x] Rename webhook container to manager

- hack/tools/fetch-images/main.go
- make/addons.mk
Noticed that the kube-vip image was missing in the last release. This is because kube-vip is deployed as a static Pod and not as a Helm chart.
<details>
<summary>$ make list-images</summary>
```
docker.io/nutanix/ntnx-csi-precheck:3.0.0
docker.io/nutanix/ntnx-csi:3.0.0
docker.io/rancher/local-path-provisioner:v0.0.30
ghcr.io/kube-vip/kube-vip:v0.8.3
ghcr.io/nutanix-cloud-native/caren-helm-reg:v0.0.0-dev
ghcr.io/nutanix-cloud-native/cloud-provider-nutanix/controller:v0.4.1
ghcr.io/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix:v0.0.0-dev
public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.35.0
public.ecr.aws/eks-distro/kubernetes-csi/external-attacher:v4.7.0-eks-1-31-3
public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner:v5.1.0-eks …
```
> fix: include kube-vip image in generated caren-images.txt

- hack/tools/fetch-images/main.go
Without this change the script always returned the latest Chart versions, not those defined in the repo
```
➜  CAREN_VERSION=v0.18.0 make list-images > fixed-images.txt
➜  diff fixed-images.txt caren-images.txt
3c3
< docker.io/rancher/local-path-provisioner:v0.0.27
---
> docker.io/rancher/local-path-provisioner:v0.0.30
8,14c8,14
< public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.35.0
< public.ecr.aws/eks-distro/kubernetes-csi/external-attacher:v4.7.0-eks-1-31-3
< public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner:v5.1.0-eks-1-31-3
< public.ecr.aws/eks-distro/kubernetes-csi/external-resizer:v1.12.0-eks-1-31-3
< public.ecr.aws/eks-distro/kubernetes-csi/external-snapshotter/csi-snapshotter:v8.0.1-eks-1-31-3
< …
```
> build: pass the Chart version when listing images

- hack/addons/mindthegap-helm-registry/Dockerfile
Latest changes broke the published arm build. The `mindthegap` binary from `bundle_builder` will always be `BUILDPLATFORM`, but we want it to match `TARGETPLATFORM`.
Fixes #
> fix: bundle correct arch for the mindthegap binary

- charts/cluster-api-runtime-extensions-nutanix/README.md
- charts/cluster-api-runtime-extensions-nutanix/templates/helm-repository.yaml
- charts/cluster-api-runtime-extensions-nutanix/values.schema.json
- charts/cluster-api-runtime-extensions-nutanix/values.yaml
User `65532` is the default UID in distroless based images, but in Alpine it's a different user and group. 
Fixes #
> fix: use correct securityContext for Alpine based helm-repository Pod

- .gitignore
- .goreleaser.yml
- docs/content/getting-started/deployment/via-clusterctl.md
- test/e2e/config/caren.yaml
Noticed that the clusterctl components filename was incorrect - should be
`runtime-extensions-components.yaml` as documented at
https://cluster-api.sigs.k8s.io/clusterctl/provider-contract#components-yaml.
Will do a patch release after this change is made. This will allow adding the
provider to the upstream clusterctl provider list.
> fix: Use correct filename for runtime extensions component YAML

- hack/tools/fetch-images/main.go
Noticed in the [last release](https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/releases/download/v0.22.0/caren-images.txt) this image tag was set to `v0.0.0-dev`, fixing it to get the release version.
```
$ make list-images
...
ghcr.io/nutanix-cloud-native/caren-helm-reg:v0.22.1
```
Fixes #
> build: set helmRepository tag in list-images target

- hack/addons/mindthegap-helm-registry/Dockerfile
Previously, mindthegap required a restart rollout after its certificate was rotated. It will now use updated certificates without restarting.
Also see https://github.com/mesosphere/mindthegap/releases/tag/v1.17.0 
Fixes https://jira.nutanix.com/browse/NCN-104087
> fix: Update mindthegap to fix cert rotation

- .github/workflows/checks.yml
- .goreleaser.yml
- charts/cluster-api-runtime-extensions-nutanix/README.md
- charts/cluster-api-runtime-extensions-nutanix/values.yaml
- make/dev.mk
- test/e2e/config/caren.yaml
While looking at https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/968 I noticed the image name.
The `caren-helm-reg` image is no longer used as a registry. The word registry was also recently changed to repository in the templates.
Renamed it to `cluster-api-runtime-extensions-bundle-initializer`, but open to suggestions!
Fixes #
> build: rename caren-helm-reg to better match role

- pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files.go
- pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
- pkg/handlers/generic/mutation/imageregistries/credentials/inject_test.go
Passing `imageRegistries` with a CA but without credentials is still a valid configuration and should not error.
Fixes #
> fix: image registries with no credentials but with a CA

- charts/cluster-api-runtime-extensions-nutanix/templates/helm-repository.yaml
changes name of container to manager to ensure a clusterctl waits for this core service caren depends on to be ready.
Fixes #
> fix: set container name to manager to ensure we wait for it

- .gitignore
- .goreleaser.yml
- hack/examples/release/add-version-to-clusterclasses.sh
- hack/examples/release/kustomization.yaml.tmpl
- make/goreleaser.mk
This attaches the updated cluster class artifacts containing the
CAREN release version to the release artifacts on release.
> build: Add CAREN release to cluster class artifacts

- pkg/handlers/generic/lifecycle/addons/helmaddon.go
- pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
This PR is a small refactor to pull existing functionality into the common addon applier. I wanted similar functionality in another handler to wait for the HCP to be ready. 
Fixes #
> refactor: new waiter functionality in helmAddonApplier

- pkg/handlers/generic/lifecycle/addons/helmaddon.go
Only checking for HelmReleaseReadyCondition may not be enough, especially during cluster upgrades where the values in the HCP have changed.
Fixes #
> fix: check HelmReleaseReadyCondition when status is up-to-date

- .github/dependabot.yml
The existing configuration still allowed pre-release updates and there is no way to configure this. Removing the update-types means this will always be ignored and only updated when the NCN ntnx client is updated.
Fixes #
> build: Properly ignore ntnx API client from dependabot

- api/versions/coredns.go
- api/versions/coredns_test.go
Adds CoreDNS version mapping for Kubernetes v1.32
Fixes #
> fix: update CoreDNS mapping file

- api/v1alpha1/common_types.go
- api/v1alpha1/common_types_test.go
- api/v1alpha1/nutanix_clusterconfig_types.go
- api/v1alpha1/nutanix_clusterconfig_types_test.go
- pkg/helpers/helpers.go
- pkg/helpers/helpers_test.go
- pkg/webhook/cluster/nutanix_validator.go
- pkg/webhook/cluster/nutanix_validator_test.go
- pkg/webhook/cluster/validator.go
webhook errors out if NUTANIX_ENDPOINT IP falls in Load Balancer IP Range. It only implements dumb check which compares PC IP with Load Balancer IP Range. It's complex to achieve with CEL so going with webhook as we'll need to use regex(isIP() func is not working for cluster variables) to extract IP from PC URL and do string compare which not robust as we can do error handling through webhook.
Fixes #
https://jira.nutanix.com/browse/NCN-102628
```
✗ clusterctl generate cluster ${CLUSTER_NAME} \  --from ${CLUSTER_FILE} \
--kubernetes-version ${KUBERNETES_VERSION} \
--worker-machine-count 1 | \
kubectl apply --server-side -f - …
```
> fix: validates PC IP is outside Load Balancer IP Range

- charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
- hack/addons/helm-chart-bundler/repos.yaml
- make/addons.mk
Pulls in the changes from https://github.com/mesosphere/charts/pull/1531/files
Fixes #
> fix: update COSI controller image to fix CVEs

- test/e2e/addon_helpers.go
- test/e2e/cosi_helpers.go
Missed this in https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/1008 since I thought that all HCP are already checked.
Fixes #
> test: wait for COSI controller to be ready

- charts/cluster-api-runtime-extensions-nutanix/templates/helm-repository.yaml
During upgrades the init container was incorrectly copying the whole directory, instead of just the tars.
```
$ ls /helm-charts/bundles/
charts                   helm-charts-v0.14.6.tar  helm-charts-v0.14.9.tar  helm-charts-v0.23.1.tar
$ ls /helm-charts/bundles/charts/
helm-charts-v0.14.6.tar  helm-charts-v0.14.9.tar  helm-charts-v0.25.0.tar
```
Fixes #
The file gets copied correctly when the directory does not exist:
```
$ cp -r charts/ dst/
$ ls dst
foo.tar
```
When the dir already exists (ie upgrade scenario), the whole directory gets copied:
```
$ mkdir dst
$ cp -r charts/ dst/
$ ls dst
charts
```
Copying the file works correctly into an existing dst if using .:
```
$ mkdir dst
$ cp …
```
> fix: correctly copy Helm charts in init container

- charts/cluster-api-runtime-extensions-nutanix/README.md
- charts/cluster-api-runtime-extensions-nutanix/values.yaml
The helm-repository container is defaulting to the wrong mindthegap version, one that is missing an [important fix](https://github.com/mesosphere/mindthegap/pull/805).
Fixes https://jira.nutanix.com/browse/NCN-104087
> fix: Use mindthegap v1.17.0 for the helm-repository container

- charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
- hack/addons/helm-chart-bundler/repos.yaml
- make/addons.mk
The `gcr.io/k8s-staging-sig-storage` repository is being shut down. Temporarily moving the image until upstream moves it to a more permanent location.
This pulls in the changes:
- https://github.com/mesosphere/charts/pull/1542
- https://github.com/mesosphere/charts/pull/1543
Fixes #
The e2e tests will verify the controller is running.
I've also verified the image by following the examples in https://github.com/nutanix-cloud-native/cosi-driver-nutanix 
> fix: use republished COSI controller image

- api/v1alpha1/addon_types.go
- api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
- api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
- api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
- docs/content/addons/cni.md
- pkg/handlers/generic/lifecycle/cni/cilium/handler.go
- pkg/handlers/generic/lifecycle/cni/variables_test.go
implementation for user defined cilium configmap in cluster creation, current PR's implementation covers only configmap kind and assumes that `clusterctl.cluster.x-k8s.io/move` label is added on configmap by user. 
pending PRs:
1. Implementation for Secret kind object for user defined cilium spec.
Fixes #
[NCN-105148](https://jira.nutanix.com/browse/NCN-105148)
```
$ kg cluster
NAME               CLUSTERCLASS          PHASE         AGE   VERSION
nkp-mgmt-cluster   nutanix-quick-start   Provisioned   15m   v1.31.4
$ kg cm custom-cilium-cni-helm-values-template -oyaml
apiVersion: v1
data:
values.yaml: |-
cni:
chainingMode: portmap
exclusive: false …
```
> feat: implementation for user defined configmap for cilium addon in cluster creation

- docs/content/addons/cni.md
- pkg/handlers/generic/lifecycle/ccm/nutanix/handler.go
- pkg/handlers/generic/lifecycle/cni/cilium/handler.go
- pkg/handlers/generic/lifecycle/csi/nutanix/handler.go
- pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
- pkg/handlers/utils/secrets.go
- pkg/handlers/utils/secrets_test.go
Adds cluster's ownerref on cilium helm values source object so users won't have to explicitly need to add `clusterctl.cluster.x-k8s.io/move: ""` label
Fixes #
NCN-105148
```
apiVersion: v1
data:
values.yaml: |-
cni:
chainingMode: portmap
exclusive: false
hubble:
enabled: true
tls:
auto:
enabled: true               # enable automatic TLS certificate generation
method: cronJob             # auto generate certificates using cronJob method
certValidityDuration: 60    # certificates validity duration in days (default 2 months)
schedule: "0 0 5 * *"       # schedule on the 1st day regeneration of each month
relay:
enabled: true
image:
useDigest: false
ipam: …
```
> feat: adds cluster's ownerref on cilium helm values source object

- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/nutanix-cluster-class.yaml
- hack/examples/overlays/clusterclasses/nutanix/kustomization.yaml.tmpl
- pkg/handlers/deleteinv0280/generic/mutation/handlers.go
- pkg/handlers/deleteinv0280/generic/mutation/mirrors/containerd_files.go
- pkg/handlers/deleteinv0280/generic/mutation/mirrors/containerd_files_test.go
- pkg/handlers/deleteinv0280/generic/mutation/mirrors/inject.go
- pkg/handlers/deleteinv0280/generic/mutation/mirrors/inject_test.go
- pkg/handlers/deleteinv0280/generic/mutation/mirrors/templates/containerd-registry-config-drop-in.toml
- pkg/handlers/deleteinv0280/generic/mutation/mirrors/templates/hosts.toml.gotmpl
- pkg/handlers/deleteinv0280/generic/mutation/mirrors/variables_test.go
- pkg/handlers/deleteinv0280/nutanix/mutation/metapatch_handler.go
- pkg/handlers/generic/mutation/mirrors/containerd_files.go
- pkg/handlers/generic/mutation/mirrors/containerd_files_test.go
- pkg/handlers/generic/mutation/mirrors/inject.go
- pkg/handlers/generic/mutation/mirrors/inject_test.go
- pkg/handlers/generic/mutation/mirrors/templates/hosts.toml.gotmpl
- pkg/handlers/nutanix/handlers.go
This PR updates the runtime extensions to include two mutation handlers for Nutanix clusters:
- `nutanixclusterconfigpatch-gp.cluster-api-runtime-extensions-nutanix` - original name and original (buggy functionality). This will still be referenced from existing CCs and so must retain the same name.
- `nutanixclusterv2configpatch-gp.cluster-api-runtime-extensions-nutanix` - new name with fixed functionality. This is now referenced from the example CC in this project and can be used by existing clusters by rebasing on a CC that references this handler name.
The new handler fixes are:
- CA certificates are now written to `/etc/containerd/certs.d/<registryHost>/ca.crt`
as per https://github.com/containerd/containerd/blob/main/docs/hosts.md#support-for-dockers-certificate-file-pattern. This …
> fix: Correctly configure non-mirror registry certificates

- charts/cluster-api-runtime-extensions-nutanix/addons/cni/cilium/values-template.yaml
Assigns the `system-cluster-critical` PriorityClassName to Hubble. This is the same class name assigned to Cilium itself.
Fixes https://jira.nutanix.com/browse/NCN-105637
> fix: Configure priorityClassName for Cilium Hubble

- pkg/handlers/generic/mutation/mirrors/containerd_files.go
- pkg/handlers/generic/mutation/mirrors/containerd_files_test.go
- pkg/handlers/generic/mutation/mirrors/inject_test.go
Now that we're fixing how the `_default` file is being generated just for mirrors, we should skip creating the file if only registries are provided.
Depends on #1039.
Fixes #
> fix: don't generate empty _default containerd mirror file

- charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
- hack/addons/helm-chart-bundler/repos.yaml
- make/addons.mk
Chart now defines priorityClass and tolerations for the controller Pod.
Fixes https://jira.nutanix.com/browse/NCN-105644
> feat: Update COSI controller Addon

- make/dev.mk
- pkg/handlers/deleteinv0280/generic/mutation/handlers.go
- pkg/handlers/deleteinv0280/generic/mutation/imageregistries/credentials/credential_provider_config_files.go
- pkg/handlers/deleteinv0280/generic/mutation/imageregistries/credentials/credential_provider_config_files_test.go
- pkg/handlers/deleteinv0280/generic/mutation/imageregistries/credentials/credential_provider_install_files.go
- pkg/handlers/deleteinv0280/generic/mutation/imageregistries/credentials/credential_provider_kubelet_args.go
- pkg/handlers/deleteinv0280/generic/mutation/imageregistries/credentials/credentials_secret.go
- pkg/handlers/deleteinv0280/generic/mutation/imageregistries/credentials/credentials_secret_test.go
- pkg/handlers/deleteinv0280/generic/mutation/imageregistries/credentials/doc.go
- pkg/handlers/deleteinv0280/generic/mutation/imageregistries/credentials/inject.go
- pkg/handlers/deleteinv0280/generic/mutation/imageregistries/credentials/inject_test.go
- pkg/handlers/deleteinv0280/generic/mutation/imageregistries/credentials/templates/dynamic-credential-provider-config.yaml.gotmpl
- pkg/handlers/deleteinv0280/generic/mutation/imageregistries/credentials/templates/install-kubelet-credential-providers.sh.gotmpl
- pkg/handlers/deleteinv0280/generic/mutation/imageregistries/credentials/templates/kubelet-image-credential-provider-config.yaml.gotmpl
- pkg/handlers/deleteinv0280/generic/mutation/imageregistries/credentials/templates/static-credential-provider.json.gotmpl
- pkg/handlers/deleteinv0280/generic/mutation/imageregistries/credentials/variables_test.go
- pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files.go
- pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files_test.go
- pkg/handlers/generic/mutation/imageregistries/credentials/templates/dynamic-credential-provider-config.yaml.gotmpl
Only allowed a single configuration per provider binary so match up
the image hosts per binary in the config.
Depends on #1039.
> fix: Correctly configure dynamic credential provider

- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/aws-cluster-class.yaml
- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/docker-cluster-class.yaml
- hack/examples/overlays/clusterclasses/aws/kustomization.yaml.tmpl
- hack/examples/overlays/clusterclasses/docker/kustomization.yaml.tmpl
- pkg/handlers/aws/handlers.go
- pkg/handlers/deleteinv0280/aws/mutation/metapatch_handler.go
- pkg/handlers/deleteinv0280/docker/mutation/metapatch_handler.go
- pkg/handlers/deleteinv0280/generic/mutation/metapatch_handler.go
- pkg/handlers/docker/handlers.go
- pkg/handlers/generic/handlers.go
This means no automatic rollout of clusters using the existing
ClusterClasses and will not break any downstream project tests
that might be checking for that.
Same approach as previously done for Nutanix ClusterClass -
should have done this at the same time.
> fix: Use new patch handler for AWS and Docker ClusterClasses

- .goreleaser.yml
`kos.repository` is deprecated so update it to remove warning in logs.
> build: Updated goreleaser kos.repositories config

- pkg/handlers/generic/mutation/mirrors/containerd_files.go
- pkg/handlers/generic/mutation/mirrors/containerd_files_test.go
Write out a single CA file for multiple registries with the same url.Host. Return an error if the CA content for those registries do not match.
This fix is needed after another recent fix https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/1039/commits/17bc80da9bfe98670c2af6c7d16b67475acd4564#diff-3b57926153158559026700fdb9392d259a62201d7eb485f3d0d62fdeaa976ffdL57-L64 that now correctly generates the CA files without the url.Path.
Fixes #
New unit tests.
> fix: correctly handle multiple registries with the same Host

- charts/cluster-api-runtime-extensions-nutanix/addons/serviceloadbalancer/metallb/values-template.yaml
What problem does this PR solve?:
Adds an override for frr routing
Which issue(s) this PR fixes:
Fixes # pkg:docker/frrouting/frr@9.1.0?repository_url=quay.io
How Has This Been Tested?:
Special notes for your reviewer:
arvinder.pal@GHH4XN27GC kubetunnel % trivy i quay.io/frrouting/frr:9.1.3 --severity=HIGH,MEDIUM
2025-02-26T10:50:16+05:30	INFO	[db] Need to update DB
2025-02-26T10:50:16+05:30	INFO	[db] Downloading DB...	repository="ghcr.io/aquasecurity/trivy-db:2"
59.46 MiB / 59.46 MiB [-----------------------------------------------------------------------] 100.00% 3.06 MiB p/s 20s
2025-02-26T10:50:38+05:30	INFO	[vuln] Vulnerability scanning is enabled
2025-02-26T10:50:38+05:30	INFO	[secret] Secret scanning is enabled
2025-02-26T10:50:38+05:30	INFO	[secret] If your scanning is slow, …
> feat: bumped frr-routing to 9.1.3

- charts/cluster-api-runtime-extensions-nutanix/addons/csi/aws-ebs/values-template.yaml
- charts/cluster-api-runtime-extensions-nutanix/addons/csi/local-path/values-template.yaml
- charts/cluster-api-runtime-extensions-nutanix/addons/csi/nutanix/values-template.yaml
- charts/cluster-api-runtime-extensions-nutanix/addons/nfd/values-template.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/csi/aws-ebs/manifests/aws-ebs-csi-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/csi/local-path/manifests/local-path-provisioner-csi-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/node-feature-discovery-configmap.yaml
This allows tainting nodepools and still using e.g. GPUs or CSI.
> fix: Tolerate all NoSchedule taints for NFD and CSI deployments

- .github/dependabot.yml
These are skipped by dependabot which ignores `k8s.io/*` in order for
dependencies in order to retain compatibility with `sigs.k8s.io/controller-runtime`,
but as `controller-runtime` does not have dependencies on `k8s.io/kubelet` then it
gets skipped on update. This commit brings it up to date.
> build: Update k8s.io/{kubelet,utils} deps

- .github/dependabot.yml
Reverts nutanix-cloud-native/cluster-api-runtime-extensions-nutanix#1078
This actually led to broken PRs - let's manually update the other dependencies when we need to instead.
> revert: "build: Update k8s.io/{kubelet,utils} deps"

- .github/workflows/checks.yml
This allows us to change patch versions without having to update required
checks.
> ci: Use Kubernetes minor in e2e check name

- charts/cluster-api-runtime-extensions-nutanix/addons/cni/cilium/values-template.yaml
Enables mTLS. The hubble relay server was already always enabled, this PR also enables its mTLS configuration.
Fixes #
> feat: enable Cilium's hubble relay mTLS

- devbox.lock
new version of devbox is out and it makes a small change to the devbox.lock. Committing the change to prevent failing builds.
> fix(deps): update devbox.lock

- api/go.mod
- common/go.mod
- go.mod
Fixes https://pkg.go.dev/vuln/GO-2025-3563.
> feat: go 1.24.2 to fix CVE

- README.md
- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/aws-cluster-class.yaml
- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/docker-cluster-class.yaml
- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/nutanix-cluster-class.yaml
- docs/content/getting-started/integrating-with-your-clusterclass/_index.md
- hack/examples/overlays/clusterclasses/aws/kustomization.yaml.tmpl
- hack/examples/overlays/clusterclasses/docker/kustomization.yaml.tmpl
- hack/examples/overlays/clusterclasses/nutanix/kustomization.yaml.tmpl
- pkg/handlers/aws/handlers.go
- pkg/handlers/aws/mutation/metapatch_handler.go
- pkg/handlers/docker/handlers.go
- pkg/handlers/docker/mutation/metapatch_handler.go
- pkg/handlers/generic/handlers.go
- pkg/handlers/generic/mutation/metapatch_handler.go
- pkg/handlers/nutanix/handlers.go
- pkg/handlers/nutanix/mutation/metapatch_handler.go
- pkg/handlers/v2/aws/mutation/metapatch_handler.go
- pkg/handlers/v2/docker/mutation/metapatch_handler.go
- pkg/handlers/v2/generic/mutation/handlers.go
- pkg/handlers/v2/generic/mutation/metapatch_handler.go
- pkg/handlers/v2/nutanix/mutation/metapatch_handler.go
When adding https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/1097, we effectively enabled this handler by default through API defaults. I wrongly assumed that the worker and control-plane handlers were behind a new version of the handlers registration. And because its not, this caused a rollout of all Machines when CAREN is upgraded on the management cluster.
This PR puts the worker and control-plane handlers behind a new version of the hooks and does not include the new `noderegistration` handler in the older version of the hooks.
Fixes #
Tested locally by upgrading the handler version and observing that Machines were NOT rolled out. We will need some …
> fix: use a new version for control-plane and worker mutation handlers

- hack/third-party/capx/go.mod
- hack/third-party/capx/go.sum
Update CAPX version to v1.6.1 and run `make apis.sync`
> build(deps): Update CAPX to v1.6.1

- make/addons.mk
Noticed after the release we're still using the kube-vip image `v0.8.9` from the old handler.
With this change:
```
➜  cluster-api-runtime-extensions-nutanix git:(dkoshkin/ci-include-correct-kube-vip-version) ✗ make list-images | grep kube-vip
ghcr.io/kube-vip/kube-vip:v0.8.10
```
Fixes #
> ci: include correct kube-vip version when listing images

- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/aws-cluster-class.yaml
- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/docker-cluster-class.yaml
- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/nutanix-cluster-class.yaml
- hack/examples/overlays/clusterclasses/aws/kustomization.yaml.tmpl
- hack/examples/overlays/clusterclasses/docker/kustomization.yaml.tmpl
- hack/examples/overlays/clusterclasses/nutanix/kustomization.yaml.tmpl
- hack/examples/patches/disable-kubeadmcontrolplane-profiling.yaml
As per CIS benchmarks 1.2.15, 1.3.2 and 1.4.1.
Requires #1111.
> feat: Explicitly disable profiling for CP components

- test/e2e/quick_start_test.go
- test/e2e/self_hosted_test.go
These are currently unused and causing numerous flakes. Disabling until
we get time to properly investigate and fix.
> test(e2e): Disable Calico tests

- .github/workflows/checks.yml
No need to run this any more, just keeping on top of number of
checks we run.
Requires #1121.
> ci: Remove Docker k8s v1.30 e2e test in GHA

- pkg/handlers/generic/lifecycle/ccm/nutanix/handler_test.go
Fixes the test helper when `go.work` is used locally.
Previously, the helper returned all the output of `go list -m`, and when using go.work, the output contains multiple lines, with the directory of the root module on the first line. Now, the helper returns only the first line.
The previous behavior caused the test to fail:
```
=== Failed
=== FAIL: pkg/handlers/generic/lifecycle/ccm/nutanix Test_templateValues (0.00s)
handler_test.go:71:
Error Trace:	/home/dlipovetsky/projects/cluster-api-runtime-extensions-nutanix/pkg/handlers/generic/lifecycle/ccm/nutanix/handler_test.go:193
/home/dlipovetsky/projects/cluster-api-runtime-extensions-nutanix/pkg/handlers/generic/lifecycle/ccm/nutanix/handler_test.go:71
Error:      	Received unexpected error:
open …
```
> test: Return root module root dir when using go.work

- pkg/handlers/generic/mutation/mirrors/inject.go
- pkg/handlers/generic/mutation/mirrors/inject_test.go
Depends on https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/1116
Automatically sets the registryMirror as a Containerd mirror. We're not updating the Cluster object because this should not be a user controller configuration and the IP used as the mirror is determined based on the addon handler and the Service CIDRs.
Tested in a Docker cluster:
```
$ kubectl port-forward \
--address=0.0.0.0 \
--namespace registry-mirror-system \
pod/registry-mirror-docker-registry-0 5000:5000
$ crane copy nginx:latest 0.0.0.0:5000/library/nginx:dkoshkin --insecure
$ kubectl run nginx-working --image=docker.io/library/nginx:dkoshkin
$ kubectl run nginx-should-be-broken --image=docker.io/library/nginx:dne
$ kubectl get pods 
NAME …
```
> feat: use registryMirror addon as Containerd mirror

- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/aws-cluster-class.yaml
- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/nutanix-cluster-class.yaml
- common/pkg/capi/clustertopology/variables/variable.go
- common/pkg/testutils/capitest/patches.go
- common/pkg/testutils/capitest/request/items.go
- hack/examples/bases/aws/clusterclass/kustomization.yaml.tmpl
- hack/examples/bases/nutanix/clusterclass/kustomization.yaml.tmpl
- pkg/handlers/generic/mutation/externalcloudprovider/inject.go
- pkg/handlers/generic/mutation/externalcloudprovider/inject_test.go
- pkg/handlers/generic/mutation/handlers.go
This flag has been removed from kube-apiserver in k8s v1.33 so need to
use version specific logic to add it for pre-1.33 clusters.
> feat: Add k8s version logic for external cloud-provider flag

- charts/cluster-api-runtime-extensions-nutanix/addons/registry/cncf-distribution/values-template.yaml
Set requests and limits for the registry containers. The addon can be enabled in every cluster so we want to have control over the resources.
These numbers were collected by pushing a 12GB bundle to the registry.
Fixes #
> feat: add requests and limits to registry containers

- charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
- hack/addons/helm-chart-bundler/repos.yaml
- hack/addons/kustomize/cncf-distribution-registry/kustomization.yaml.tmpl
Updates chart version that has a fix that correctly sets headless service port equal to pod's port.
Usually clients would explicitly set the port directly when connecting to the headless service, but this does fix using `kubectl port-forward`
Fixes #
```
$ kubectl port-forward --address=127.0.0.1 --namespace registry-system service/cncf-distribution-registry-docker-registry-headless https
Forwarding from 127.0.0.1:5000 -> 5000
Handling connection for 5000
$ crane copy nginx:stable 127.0.0.1:5000/library/nginx:dkoshkin --insecure                                                                      
2025/06/13 13:51:08 Copying from nginx:stable to 127.0.0.1:5000/library/nginx:dkoshkin …
```
> fix: registry addon headless service port

- pkg/webhook/preflight/preflight.go
- pkg/webhook/preflight/preflight_test.go
- pkg/webhook/preflight/skip/skip.go
- pkg/webhook/preflight/skip/skip_test.go
Provides a way for the client to opt out of preflight checks for a specific Cluster by using an annotation:
Examples
Opt out of two specific checks:
```
preflight.cluster.caren.nutanix.com/opt-out: "CheckOne, checktwo"
```
(Note that both case and whitespace is ignored)
Opt out of all checks:
```
preflight.cluster.caren.nutanix.com/opt-out: all
```
When a pre-flight check returns a false negative due to a bug, an issue in some external API, or some unforseen circumstance, the client needs a way to opt out. 
Fixes #
> feat: Preflight check opt-out

- charts/cluster-api-runtime-extensions-nutanix/README.md
- charts/cluster-api-runtime-extensions-nutanix/templates/deployment.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/role.yaml
- charts/cluster-api-runtime-extensions-nutanix/values.schema.json
- charts/cluster-api-runtime-extensions-nutanix/values.yaml
- cmd/main.go
- internal/test/builder/builders.go
- pkg/controllers/enforceclusterautoscalerlimits/controller.go
- pkg/controllers/enforceclusterautoscalerlimits/controller_test.go
- pkg/controllers/enforceclusterautoscalerlimits/doc.go
- pkg/controllers/enforceclusterautoscalerlimits/flags.go
- pkg/controllers/enforceclusterautoscalerlimits/suite_test.go
- pkg/controllers/namespacesync/controller.go
When the current MD `.spec.replicas` is outside of the bounds of the cluster autoscaler min/max annotations, cluster autoscaler will not scale the MD up or down. This can occur when either the annotations are edited or `spec.replicas` is updated.
In a topology-based cluster, CAPI propagates the cluster autoscaler annotations from `cluster.spec.topology.workers.machineDeployments[].metadata.annotations` to the templated `MachineDeployment` resources. If these annotations are changed so that the range they define does not contain the current number of replicas, then no scaling up or down will happen to the MachineDeployment by the cluster autoscaler.
This commit adds a controller that does the following to MachineDeployments:
- if `spec.replicas` is nil do nothing
- if cluster autoscaler …
> feat: Enforce MD replicas within cluster autoscaler bounds

- docs/content/addons/cni.md
- docs/content/addons/cosi.md
- docs/content/addons/registry.md
I messed up the link in #1173, sorry! At the same time I noticed icons being reused so cleaned those up so things are pretty again!
Fixes #
> docs: Fix up Cilium config link (again) & icons

- pkg/webhook/preflight/preflight.go
- pkg/webhook/preflight/preflight_test.go
When clusterctl moves the Cluster, clusterctl first creates a paused Cluster object, then the referenced Secrets. That order might be a bug. However, to allow move to work, we want to skip preflight checks.  
Fixes #
> fix: Do not run preflight checks if Cluster is paused

- pkg/webhook/preflight/nutanix/image_test.go
- pkg/webhook/preflight/nutanix/storagecontainer.go
- pkg/webhook/preflight/nutanix/storagecontainer_test.go
- Handle nil responses of get storage container and get cluster API calls.
- Improve error wording. 
- Correctly construct error responses of list API calls.
- Test error response of list clusters API call.
- Treat a missing storageContainer as a failed check, but not an internal error.
> fix(preflight): improved error reporting for storage container and VM image checks

- pkg/webhook/preflight/nutanix/checker.go
- pkg/webhook/preflight/nutanix/checker_test.go
- pkg/webhook/preflight/nutanix/image.go
- pkg/webhook/preflight/nutanix/image_test.go
- pkg/webhook/preflight/nutanix/imagekubernetesversioncheck.go
- pkg/webhook/preflight/nutanix/imagekubernetesversioncheck_test.go
This check ensures images that have the standard NKP naming scheme have the image with the same kubernetes version as the cluster version.
**How has this been tested?**
create a cluster using `nkp create cluster nutanix --dry-run` and tweak the image kubernetes version to be different from cluster kubernetes version.
```
$ cat cluster.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
...
name: nkp-sid
namespace: default
spec:
...
topology:
...
variables:
- name: clusterConfig
value:
...
controlPlane:
nutanix:
machineDetails:
...
image:
name: nkp-rocky-9.5-release-1.31.4-20250214003015.qcow2
type: name
version: v1.32.3
workers:
machineDeployments:
- class: default-worker
...
name: md-0
variables:
overrides:
- name: workerConfig
value:
nutanix:
machineDetails:
...
image: …
```
> feat(preflight): Add VM Image kubernetes version check

- pkg/webhook/preflight/generic/registry.go
- pkg/webhook/preflight/generic/registry_test.go
- pkg/webhook/preflight/generic/spec.go
- pkg/webhook/preflight/generic/spec_test.go
- pkg/webhook/preflight/nutanix/credentials.go
- pkg/webhook/preflight/nutanix/credentials_test.go
- pkg/webhook/preflight/nutanix/image.go
- pkg/webhook/preflight/nutanix/image_test.go
- pkg/webhook/preflight/nutanix/imagekubernetesversioncheck.go
- pkg/webhook/preflight/nutanix/imagekubernetesversioncheck_test.go
- pkg/webhook/preflight/nutanix/specs.go
- pkg/webhook/preflight/nutanix/specs_test.go
- pkg/webhook/preflight/nutanix/storagecontainer.go
- pkg/webhook/preflight/nutanix/storagecontainer_test.go
- pkg/webhook/preflight/preflight.go
- pkg/webhook/preflight/preflight_test.go
Internal errors are meant to signal some unexpected failure. We have been treating a number of expected failures as internal errors, and this PR fixes these.
Fixes #
> fix: Do not treat expected preflight check failures as internal errors

- pkg/webhook/preflight/nutanix/imagekubernetesversioncheck.go
- pkg/webhook/preflight/nutanix/imagekubernetesversioncheck_test.go
kubernetes version can include extraneous values other than major.minor.patch. e.g. "1.33.1+fips.0".
While our image builder conventions include kubernetes major, minor, and patch versions in the image name, they don't include extraneous info as part of kubernetes version. To ensure our check only matches the right parts of the image name, we sanitize the kubernetes version before doing a substring match.
> fix(preflight): sanitize kubernetes version for image name preflight check

- pkg/webhook/preflight/generic/registry.go
- pkg/webhook/preflight/generic/registry_test.go
- pkg/webhook/preflight/nutanix/credentials.go
- pkg/webhook/preflight/nutanix/credentials_test.go
- pkg/webhook/preflight/nutanix/image.go
- pkg/webhook/preflight/nutanix/image_test.go
- pkg/webhook/preflight/nutanix/imagekubernetesversioncheck.go
- pkg/webhook/preflight/nutanix/imagekubernetesversioncheck_test.go
- pkg/webhook/preflight/nutanix/specs.go
- pkg/webhook/preflight/nutanix/specs_test.go
- pkg/webhook/preflight/nutanix/storagecontainer.go
- pkg/webhook/preflight/nutanix/storagecontainer_test.go
Fixes some issues with the check results, including:
- Make the field more precise
- Capitalize messages
- Use valid JSONPath in fields
Also:
- Remove code that is never expected to run
- Do not treat invalid credentials as an internal error
Fixes #
All changes covered by unit tests.
> fix: Misc. fixes to preflight check results

- pkg/webhook/preflight/generic/registry_test.go
- pkg/webhook/preflight/generic/spec_test.go
- pkg/webhook/preflight/nutanix/credentials.go
- pkg/webhook/preflight/nutanix/image.go
- pkg/webhook/preflight/nutanix/imagekubernetesversioncheck.go
- pkg/webhook/preflight/nutanix/imagekubernetesversioncheck_test.go
- pkg/webhook/preflight/nutanix/specs.go
- pkg/webhook/preflight/nutanix/specs_test.go
- pkg/webhook/preflight/nutanix/storagecontainer.go
- pkg/webhook/preflight/nutanix/storagecontainer_test.go
There was an extra period in a field, introduced when I manually split the field across two lines, to appease the linter. Fields are long strings, and easier to read and maintain if we don't split them up.
Fixes #
> fix: Fix typo in field name; use one-line strings to prevent future typos

- pkg/webhook/preflight/nutanix/imagekubernetesversioncheck.go
- pkg/webhook/preflight/nutanix/imagekubernetesversioncheck_test.go
- Return an internal error only when parsing fails.
- Add more context to messages.
Fixes #
> fix: Nuanced image Kubernetes version check errors

- pkg/webhook/preflight/nutanix/checker.go
- pkg/webhook/preflight/nutanix/specs.go
- pkg/webhook/preflight/nutanix/storagecontainer.go
- pkg/webhook/preflight/nutanix/storagecontainer_test.go
https://jira.nutanix.com/browse/NCN-108172
Ensure all existing preflight checks are also handling failure domains
For 2.16, just to skip the preflight checks that depends on the PE cluster configuration.
Added corresponding unit tests.
> feat: Skip FD dependent preflight checks when failureDomain configured

- charts/cluster-api-runtime-extensions-nutanix/templates/role.yaml
- cmd/main.go
- pkg/controllers/failuredomainrollout/controller.go
- pkg/controllers/failuredomainrollout/controller_test.go
- pkg/controllers/failuredomainrollout/doc.go
- pkg/controllers/failuredomainrollout/flags.go
Adds a new controller that monitors cluster.status.failureDomains and triggers rollouts on KubeAdmControlPlane when failure domains currently in use by control plane machines are disabled or removed.
The controller is enabled by default and can be disabled with --failure-domain-rollout-enabled=false.
**How has this been tested?**
* Create 4 failure domains: fd-1, fd-2, fd-3, fd-4
* Create a cluster with control plane on 3 failure domains fd-1, fd-2, fd-3
* Remove fd-3 from the control plane configuration and observe a rollout to fd-1 & fd-2 only
* Add fd-3 again and observe a rollout to fd-1, fd-2, and fd-3
* Add fd-4 to control plane configuration and observe no rollout takes place
> feat(failuredomains): add failure domain rollout controller

- charts/cluster-api-runtime-extensions-nutanix/README.md
- charts/cluster-api-runtime-extensions-nutanix/templates/deployment.yaml
- charts/cluster-api-runtime-extensions-nutanix/values.schema.json
- charts/cluster-api-runtime-extensions-nutanix/values.yaml
helm config can be used to enable/disable the controller and to set concurrency.
> fix(helm): add failuredomain rollout controller config to helm chart 

- pkg/webhook/preflight/nutanix/clients_test.go
- pkg/webhook/preflight/nutanix/storagecontainer.go
- pkg/webhook/preflight/nutanix/storagecontainer_test.go
If control plane or a machine deployment uses failure domains, use the cluster from the failure domain instead of machine details.
**How has this been tested?**
1. Misconfigured storage container (doesn't actually exist) on cluster in machine details or on cluster in failure domain (e.g. `ncn-dev-sandbox-gpu` doesn't have `k8s` storage container)
2. Create failure domain
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: NutanixFailureDomain
metadata:
name: fd-2
namespace: default
spec:
prismElementCluster:
type: name
name: ncn-dev-sandbox-gpu
subnets:
- type: name
name: subnet-2
```
3. Create a cluster
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
...
spec:
...
topology:
class: nutanix-quick-start
controlPlane:
metadata: {}
replicas: 3
variables:
...
- name: …
```
> fix(preflight): check storage containers on all failure domains

- pkg/webhook/preflight/generic/registry.go
- pkg/webhook/preflight/generic/registry_test.go
- pkg/webhook/preflight/generic/spec.go
- pkg/webhook/preflight/generic/spec_test.go
Some fields were still not using valid JSONPath. I already fixed the other fields earlier in https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/1202.
Fixes #
> fix: Use JSONPath in check result fields

- api/v1alpha1/controlplane_types.go
- api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
- api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
- api/v1alpha1/crds/caren.nutanix.com_dockerworkernodeconfigs.yaml
- api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
- common/pkg/testutils/capitest/variables.go
- common/pkg/testutils/openapi/cel.go
- common/pkg/testutils/openapi/validate.go
- pkg/handlers/generic/mutation/autorenewcerts/inject.go
- pkg/handlers/generic/mutation/autorenewcerts/inject_test.go
- pkg/handlers/generic/mutation/autorenewcerts/variables_test.go
As of now to disable CAPI based automated certificate renewal we have to set `autoRenewCertificates` to `nil` which results in SSA patch [issue](https://github.com/kubernetes/kubernetes/issues/117447). To avoid this added 0 as a valid value for `autoRenewCertificates.daysBeforeExpiry` denoting the feat is disabled.
Fixes [NCN-108329](https://jira.nutanix.com/browse/NCN-108329)
- Tested using the dev workflow along with the konvoy [changes](https://github.com/mesosphere/konvoy2/pull/3959)
> fix(auto-cert-renewal): adds 0 as valid value for daysBeforeExpiry

- pkg/controllers/namespacesync/controller.go
- pkg/controllers/namespacesync/controller_test.go
- pkg/controllers/namespacesync/copy.go
- pkg/controllers/namespacesync/copy_test.go
Backport of #1228
By design, the namespacesync controller does not update resources in the target namespace. However, if it only copies some resources before being interrupted (i.e. the controller restarts), it will never copy the remaining resources.
This PR adds a (failing) test that simulates this scenario, and then adds a fix.
Fixes https://jira.nutanix.com/browse/NCN-108612
Fixes #
> fix: Namespacesync copies resources after partial copy failure

- pkg/webhook/preflight/nutanix/clients.go
- pkg/webhook/preflight/nutanix/clients_test.go
- pkg/webhook/preflight/nutanix/credentials_test.go
- pkg/webhook/preflight/nutanix/failuredomain.go
- pkg/webhook/preflight/nutanix/failuredomain_test.go
- pkg/webhook/preflight/nutanix/image.go
- pkg/webhook/preflight/nutanix/image_test.go
- pkg/webhook/preflight/nutanix/imagekubernetesversioncheck.go
- pkg/webhook/preflight/nutanix/imagekubernetesversioncheck_test.go
- pkg/webhook/preflight/nutanix/storagecontainer.go
- pkg/webhook/preflight/nutanix/storagecontainer_test.go
This allows us to handle context cancellation when using the Nutanix v4 go client, which itself does not support context. That, together with #1235, allows us to return check results before the API server webhook timeout. This means the client sees results, instead of an uninformative (and misleading) "failed to call webhook" error.
Notice that no results are returned.
```
│ kubectl apply --dry-run=server -f invalid-bad-prismcentral-url.yaml -v=4
I0723 12:12:17.523594 2625398 envvar.go:172] "Feature gate default state" feature="ClientsPreferCBOR" enabled=false
I0723 12:12:17.523624 2625398 envvar.go:172] "Feature gate default state" feature="InformerResourceVersion" enabled=false
I0723 12:12:17.523627 2625398 envvar.go:172] "Feature gate default …
```
> feat: Support context for all Nutanix client calls

- examples/capi-quick-start/nutanix-cluster-failuredomain-cilium-crs.yaml
- examples/capi-quick-start/nutanix-cluster-failuredomain-cilium-helm-addon.yaml
- test/e2e/config/caren.yaml
- test/e2e/quick_start_test.go
https://jira.nutanix.com/browse/NCN-107139
Add a E2E test creating a Nutanix cluster with failure domains
The FD e2e tests are added to and run as part of [checks / e2e-quick-start (Nutanix provider)].
> test: Add a E2E test creating a Nutanix cluster with failure domains

- .markdownlint.json
Maintaining a maximum line length is not necessary.
We view Markdown documents using clients that can (and do) automatically wrap text to the width of the display.
Moreover, when we render Markdown to HTML using Hugo, the most important use case for most of Markdown documentation, the line wrapping is discarded.  
We already disabled line length for code blocks. This PR just extends it to text.
Fixes #
> build: Allow arbitrary line length in markdown documents

- common/pkg/k8s/parser/parser_test.go
- common/pkg/testutils/capitest/variables.go
This fixes incorrect line numbers being reported in test failures. This was discovered as noted in https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/1257#issuecomment-3161379399.
> test: Add t.Helper() calls in nested tests

- .github/dependabot.yml
This helps handle breaking changes in CAPI core in separate PR rather than bundling with all other dependency upgrades.
Fixes #
> ci: Upgrade CAPI core minor releases in own dependabot group

- common/pkg/capi/clustertopology/handlers/mutation/meta_test.go
- common/pkg/capi/clustertopology/patches/matchers/match_test.go
- pkg/handlers/aws/mutation/ami/inject_worker_test.go
- pkg/handlers/aws/mutation/iaminstanceprofile/inject_worker_test.go
- pkg/handlers/aws/mutation/instancetype/inject_worker_test.go
- pkg/handlers/aws/mutation/placementgroup/inject_worker_test.go
- pkg/handlers/aws/mutation/securitygroups/inject_worker_test.go
- pkg/handlers/docker/mutation/customimage/inject_control_plane.go
- pkg/handlers/docker/mutation/customimage/inject_control_plane_test.go
- pkg/handlers/docker/mutation/customimage/inject_worker.go
- pkg/handlers/docker/mutation/customimage/inject_worker_test.go
- pkg/handlers/generic/mutation/containerdapplypatchesandrestart/inject_test.go
- pkg/handlers/generic/mutation/containerdmetrics/inject_test.go
- pkg/handlers/generic/mutation/containerdunprivilegedports/inject_test.go
- pkg/handlers/generic/mutation/httpproxy/inject_test.go
- pkg/handlers/generic/mutation/imageregistries/credentials/inject_test.go
- pkg/handlers/generic/mutation/mirrors/inject_test.go
- pkg/handlers/generic/mutation/noderegistration/inject_worker_test.go
- pkg/handlers/generic/mutation/ntp/inject_test.go
- pkg/handlers/generic/mutation/taints/inject_worker_test.go
- pkg/handlers/generic/mutation/users/inject_test.go
- pkg/handlers/nutanix/mutation/machinedetails/inject_worker_test.go
Pulling out the change from https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/1255/commits
Fixes #
> refactor: Use declared builtin variable name rather than string

- pkg/handlers/generic/mutation/auditpolicy/inject.go
- pkg/handlers/generic/mutation/auditpolicy/inject_test.go
Given our disk space requirements (about 1GB), the audit logs hold about 1-2 hours. By enabling compression, we can increase this by a factor of 12, i.e. 12-24 hours.
In this PR, we enable compression of audit logs. Whenever a log file is rotated, it is compressed.
Experiments show that gzip yields a compression factor of approximately 12 for audit logs, so we increase the maximum file size by that factor. We expect disk space requirements to remain the same.
Fixes #
fluent-bit should continue to work, because it supports reading log files compressed using gzip as of https://github.com/fluent/fluent-bit/pull/8585/, released in …
> perf: Enable compression of audit logs to increase retention, without changing disk space requirements

- test/e2e/framework/nutanix/client.go
Attempt to avoid RATE_LIMIT_EXCEEDED error in parallel tests.
https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/actions/runs/17841696854/job/50732997651?pr=1309#step:7:554
Fixes #
> test: reduce polling frequency on PC API

- devbox.json
- devbox.lock
Newer version fails when running an older CAPI version: 
```
$ clusterctl get kubeconfig $CLUSTER_NAME
Error: this version of clusterctl could be used only with "v1beta2" management clusters, "v1beta1" detected
```
Can switch to latest once https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/1325 is merged
Fixes #
> build: downgrade clusterctl version

- charts/cluster-api-runtime-extensions-nutanix/addons/cni/cilium/values-template.yaml
Set Cilium's configuration to preserve source IPs from external connections. See https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#client-source-ip-preservation 
Fixes #
> feat: enable Cilium source IP preservation
