nutanix-cloud-native/cluster-api-runtime-extensions-nutanix

- go.mod
- go.sum
- make/go.mk
- pkg/handlers/servicelbgc/deleter.go
- pkg/handlers/servicelbgc/deleter_test.go
- pkg/handlers/servicelbgc/handler.go
Brought across from earlier commits in the repo.
> test: Add service LB deleter test

- PROJECT
Invalid layout (old version used) and remove previously deleted
API type.
> build: Fix up kubebuilder PROJECT file

- pkg/handlers/auditpolicy/embedded/apiserver-audit-policy.yaml
@dkoshkin I think we need to update this in Konvoy as well btw.
> fix: Update to latest audit policy

- .dev-envrc
- .envrc
See https://github.com/jetpack-io/devbox/issues/1215 for details.
> build: Disable fortify hardener to enable local debugging

- cmd/main.go
- common/pkg/capi/apis/decoders.go
- common/pkg/capi/apis/schemes.go
- common/pkg/capi/apis/unstructured_fallback.go
- common/pkg/capi/clustertopology/handlers/mutation/meta.go
- common/pkg/capi/clustertopology/handlers/mutation/meta_test.go
- pkg/handlers/aws/mutation/region/inject.go
- pkg/handlers/docker/mutation/customimage/inject.go
- pkg/handlers/docker/mutation/customimage/inject_test.go
- pkg/handlers/generic/mutation/auditpolicy/inject.go
- pkg/handlers/generic/mutation/etcd/inject.go
- pkg/handlers/generic/mutation/extraapiservercertsans/inject.go
- pkg/handlers/generic/mutation/httpproxy/inject.go
- pkg/handlers/generic/mutation/kubernetesimagerepository/inject.go
Simplifies some boilerplate across various files to add these helpers.
Depends on #190.
> feat: Introduce scheme and decoder helpers

- charts/capi-runtime-extensions/README.md
- charts/capi-runtime-extensions/templates/cni/calico/manifests/aws/installation.yaml
- charts/capi-runtime-extensions/values.yaml
- pkg/handlers/generic/lifecycle/cni/calico/handler.go
> fix: Adds AWS Calico installation configmap

- .gitignore
- .goreleaser.yml
- charts/capi-runtime-extensions/templates/_helpers.tpl
- make/goreleaser.mk
- metadata.yaml
Following clusterctl provider docs.
> build: Add files for clusterctl compatibility

- hack/flakes/flake.lock
- hack/flakes/flake.nix
And use go 1.22 to build other tools.
> build: Upgrade golangci-lint to 1.56.1

- make/goreleaser.mk
> build: Remove dockerauth dependency

- hack/addons/kustomize/aws-ebs-csi/kustomization.yaml.tmpl
No change to output but a cleaner way to pull in resources using
upstream kustomization.yamls.
> build: Use kustomization.yaml from ESB CSI repo

- .github/workflows/release-please.yml
- .github/workflows/release-tag.yml
Previous branch v121 has recently been deleted.
> ci: Fix up release workflow by specifying workflow-dispatch version

- docs/go.mod
- docs/go.sum
- docs/hugo.toml
Update to latest docsy module for documentation site.
> docs: Update docsy module

- hack/examples/sync.sh
Follow up from https://github.com/d2iq-labs/cluster-api-runtime-extensions-nutanix/pull/453#discussion_r1531005370
> build: Tidy up examples sync script

- .github/pull_request_template.md
- .pre-commit-config.yaml
Moved the original PR https://github.com/d2iq-labs/cluster-api-runtime-extensions-nutanix/pull/46
Pull request template for the repository.
> docs: add pull request template for the repository

- .github/workflows/conventional-pr-title.yml
Currently release PRs are failing conventional PR title check, this fixes that.
Fixes #
> ci: Allow release as a PR type

- docs/content/customization/nutanix/machine-details.md
The other fields are required; we should point out that additionalCategories is optional.
Thanks @deepakm-ntnx for spotting this!
Fixes #
> docs: Remove additionalCategories from required fields

- metadata.yaml
- test/e2e/config/caren.yaml
- test/e2e/data/shared/v1beta1-caren/metadata.yaml
> build: Add v0.8 release metadata

- docs/content/addons/cluster-autoscaler.md
> docs: Cluster Autoscaler is deployed on the management cluster

- docs/content/getting-started/create-cluster/nutanix.md
> docs: Fix missing placeholder in "create nutanix cluster" doc

- devbox.lock
- hack/flakes/flake.lock
- hack/flakes/flake.nix
> build: Latest devbox update

- api/go.mod
- common/go.mod
- go.mod
Fixes vulnerabilities fixed in go 1.22.3 highlighted in govlncheck on main at https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/actions/runs/8996575987/job/24713298807#step:4:17.
Fixes #
> build: Use go1.22.3 toolchain to mitigate vulnerabilties

- common/pkg/testutils/capitest/patches.go
Removes unused test helper function.
Fixes #
> refactor: Remove unused test helper function

- test/helpers/envtest.go
Adds more context (working directory, command arguments) to panic. Helpful to understand why command fails.
Fixes #
> test: Add even more context to panic in envtest helper

- pkg/handlers/generic/mutation/controlplanevirtualip/inject_test.go
- pkg/handlers/generic/mutation/extraapiservercertsans/inject_test.go
Matches cluster namespace to cluster name. Thanks to @supershal, who spotted a similar issue in PR #648.
Fixes #
> test: Match cluster namespace to cluster name

- api/go.mod
- api/go.sum
- cluster-api-runtime-extensions-nutanix.code-workspace
- common/go.mod
- common/go.sum
- go.mod
- go.sum
- hack/flakes/flake.lock
- hack/flakes/flake.nix
- pkg/handlers/generic/lifecycle/clusterautoscaler/template.go
- test/e2e/e2e_suite_test.go
- test/e2e/ownerreference_helpers.go
- test/e2e/quick_start_test.go
Including updating `clusterctl`.
> feat: Bump sigs.k8s.io/cluster-api to v1.7.2

- .gitlint
> build: Ignore all gitlint rules for dependabot commits

- .pre-commit-config.yaml
- devbox.lock
- hack/flakes/flake.lock
- hack/flakes/flake.nix
> build: Update all tools

- api/go.mod
- common/go.mod
- go.mod
Saw a vulnerability in another PR https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/actions/runs/9421448501/job/25955552798?pr=699
Fixes #
> build: update Go to 1.22.4

- .golangci.yml
- pkg/handlers/generic/lifecycle/clusterautoscaler/template_test.go
- pkg/handlers/generic/lifecycle/cni/cluster_test.go
- pkg/handlers/generic/lifecycle/servicelbgc/deleter_test.go
- pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files_test.go
- pkg/handlers/generic/mutation/imageregistries/credentials/inject_test.go
- pkg/handlers/generic/mutation/mirrors/mirror_test.go
> build: Add testifylint linter

- pkg/handlers/generic/lifecycle/utils/secrets_test.go
- pkg/handlers/nutanix/mutation/machinedetails/inject.go
> refactor: Simplify code by using slices.Clone

- pkg/handlers/generic/lifecycle/utils/secrets.go
Follow up to https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/711/files 😞 
Realized that everywhere else we use this function instead. Unit tests are unchanged, and verified manually too that it all still works:
```
kind: Secret
metadata:
creationTimestamp: "2024-06-11T16:19:52Z"
labels:
cluster.x-k8s.io/provider: nutanix
name: dkoshkin-nkp-secrets-ownership-7-pc-creds-for-csi
namespace: default
ownerReferences:
- apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
name: dkoshkin-nkp-secrets-ownership-7
uid: fd102035-5f0b-4185-92d3-b08c251b775c
```
Fixes #
> refactor: consistently use the same SetOwnerReference function

- test/e2e/config/caren.yaml
To unblock PRs until this is released upstream.
> test(e2e): Use mesosphere fork with CRSBinding fix

- .github/workflows/checks.yml
> ci: Fix up image loading for lint-test-helm

- charts/cluster-api-runtime-extensions-nutanix/templates/deployment.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/helm-repository.yaml
> refactor: Use recommended "default" function syntax in helm templates

- examples/capi-quick-start/docker-cluster-calico-crs.yaml
- examples/capi-quick-start/docker-cluster-calico-helm-addon.yaml
- examples/capi-quick-start/docker-cluster-cilium-crs.yaml
- examples/capi-quick-start/docker-cluster-cilium-helm-addon.yaml
- examples/capi-quick-start/nutanix-cluster-calico-crs.yaml
- examples/capi-quick-start/nutanix-cluster-calico-helm-addon.yaml
- examples/capi-quick-start/nutanix-cluster-cilium-crs.yaml
- examples/capi-quick-start/nutanix-cluster-cilium-helm-addon.yaml
- hack/examples/bases/docker/cluster/kustomization.yaml.tmpl
- hack/examples/bases/nutanix/cluster/kustomization.yaml.tmpl
- hack/examples/patches/metallb.yaml
- pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/configuration.go
- pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
- test/e2e/addon_helpers.go
- test/e2e/config/caren.yaml
- test/e2e/quick_start_test.go
- test/e2e/resource_helpers.go
- test/e2e/self_hosted_test.go
- test/e2e/serviceloadbalancer_helpers.go
Verifies that the ServiceLoadBalancer provider MetalLB is deployed, and its configuration created, in Docker and Nutanix clusters.
Fixes #
> test: Verify ServiceLoadBalancer in e2e Docker and Nutanix tests

- pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
Simplifies code to check a condition.
Fixes #
> refactor: Use CAPI conditions check where possible

- charts/cluster-api-runtime-extensions-nutanix/templates/csi/nutanix/manifests/helm-addon-installation.yaml
> fix: Remove unused setting from Nutanix CSI chart

- metadata.yaml
- test/e2e/config/caren.yaml
- test/e2e/data/shared/v1beta1-caren/metadata.yaml
Updating the metadata versions. Lets wait until we have a v0.13.x release before merging. 
Fixes #
> build: update version in metadata files

- .github/workflows/release-please.yml
- docs/content/contributing/releasing.md
> ci: Change release-please-action to new org googleapis

- hack/third-party/capx/go.mod
- hack/third-party/capx/go.sum
https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix/releases/tag/v1.5.0-beta.2
> build(deps): Upgrade CAPX Version to v1.5.0-beta.2

- examples/capi-quick-start/nutanix-cluster-calico-crs.yaml
- examples/capi-quick-start/nutanix-cluster-calico-helm-addon.yaml
- examples/capi-quick-start/nutanix-cluster-cilium-crs.yaml
- examples/capi-quick-start/nutanix-cluster-cilium-helm-addon.yaml
- hack/examples/patches/nutanix/initialize-variables.yaml
Uses UEFI boot type as we do in konvoy https://github.com/mesosphere/konvoy2/pull/3031
Fixes #
> fix: sets uefi boot type

- pkg/handlers/generic/lifecycle/handlers.go
The lifecycle handlers are called in the order defined (after https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/845). The MetalLB serviceloadbalancer has a dependency on CNI and CCM to run first and start its deployment process.
This PR is a small optimization that moves CCM higher in the list and the serviceloadbalancer to be last with a comment on why its last.
Fixes #
> fix: reorder lifecycle handlers with serviceloadbalancer being last

- hack/addons/mindthegap-helm-registry/Dockerfile
> fix: update mindthegap

- .github/workflows/release-please.yml
- release-please-config.json
And ensure that release-please triggers on pushes to release branch.
> ci: Always bump patch on release branch

- charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/serviceloadbalancer/metallb/helm-addon-installation.yaml
- hack/addons/mindthegap-helm-registry/repos.yaml
- make/addons.mk
The current metallb version 0.48.5 ships with ffrouting/frr image that has critical CVES
```
trivy image quay.io/frrouting/frr:9.0.2
2024-09-13T13:44:13.574-0700	INFO	Vulnerability scanning is enabled
2024-09-13T13:44:13.574-0700	INFO	Secret scanning is enabled
2024-09-13T13:44:13.574-0700	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-09-13T13:44:13.574-0700	INFO	Please see also https://aquasecurity.github.io/trivy/v0.48/docs/scanner/secret/#recommendation for faster secret detection
2024-09-13T13:44:15.718-0700	INFO	Detected OS: alpine
2024-09-13T13:44:15.718-0700	INFO	Detecting Alpine vulnerabilities...
2024-09-13T13:44:15.723-0700	INFO	Number of language-specific files: 0
quay.io/frrouting/frr:9.0.2 …
```
> fix: upgrade metallb to 0.14.8

- api/go.mod
- common/go.mod
- go.mod
Fixes CVE highlighted by govulncheck.
> feat: Build with go 1.23.1

- common/pkg/capi/clustertopology/variables/fromcrdyaml.go
Updating to support latest features in Cluster API 1.8.
> feat: Support XValidations (CEL) for CC variables

- .github/workflows/e2e.yml
- test/e2e/config/caren.yaml
> test(e2e): [release/v0.14.x] Use released rocky image

- devbox.lock
make binary version match go.mod version.
> build(deps): Update clusterctl binary to v1.8.3

- charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
- hack/addons/mindthegap-helm-registry/repos.yaml
- make/addons.mk
Updates Nutanix CSI to 3.1.0.
Fixes #
> feat: update Nutanix CSI to 3.1.0

- hack/tools/coredns-versions/main.go
Previously this was including pre-releases which is not necessary at
this point.
> build: Only consider GA releases of k8s for CoreDNS version map

- docs/content/customization/generic/dns.md
> docs: Fix title of DNS customization page

- charts/cluster-api-runtime-extensions-nutanix/templates/extensionconfig.yaml
This will trigger reconciliation of all ClusterClasses that reference this
runtime extension.
> feat: Add CAREN version to ExtensionConfig

- charts/cluster-api-runtime-extensions-nutanix/README.md
- charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.27.10-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.28.10-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.29.7-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.30.6-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.31.4-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/values.yaml
- make/addons.mk
Updating AWS CCM to latest available versions.
Fixes #
Verified the images exist.
> fix: update AWS CCM to latest versions

- charts/cluster-api-runtime-extensions-nutanix/addons/nfd/values-template.yaml
NFD components were missing a PriorityClass.
Fixes
- https://jira.nutanix.com/browse/NCN-105633
- https://jira.nutanix.com/browse/NCN-105634
> fix: Specify PriorityClass for Node Feature Discovery components

- charts/cluster-api-runtime-extensions-nutanix/addons/serviceloadbalancer/metallb/values-template.yaml
Set Priority class name for metallb controller and speaker pods
https://github.com/metallb/metallb/tree/main/charts/metallb
Fixes #
https://jira.nutanix.com/browse/NCN-105635
> fix: set priority class name for metallb

- devbox.lock
> fix: release 0.27 devbox changes

- pkg/handlers/generic/mutation/mirrors/containerd_files.go
- pkg/handlers/generic/mutation/mirrors/containerd_files_test.go
> fix: correctly handle multiple registries with the same Host [Backport v0.27.x]

- charts/cluster-api-runtime-extensions-nutanix/README.md
- charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.30.8-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.31.5-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.32.1-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/cluster-autoscaler/manifests/cluster-autoscaler-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/csi/aws-ebs/manifests/aws-ebs-csi-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
- charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/node-feature-discovery-configmap.yaml
- charts/cluster-api-runtime-extensions-nutanix/values.yaml
- hack/addons/helm-chart-bundler/repos.yaml
- make/addons.mk
Updating to the latest versions of various addons.
Fixes #
> feat: update addons

- .github/dependabot.yml
> ci: Enable dependabot for hack/tools module

- test/e2e/quick_start_test.go
- test/e2e/self_hosted_test.go
Uses consistent spelling of the word "flavor"
Fixes #
> fix: uses consistent spelling

- .github/workflows/checks.yml
- .github/workflows/e2e.yml
- test/e2e/config/caren.yaml
Using fixed images with no Nutanix user present.
> test(e2e): Update Nutanix images

- charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
- hack/addons/helm-chart-bundler/repos.yaml
- hack/addons/kustomize/cncf-distribution-registry/kustomization.yaml.tmpl
This version picks up CVE fixes in the registry image.
(Updating to 3.0 will be handled as a separate PR.)
Fixes #
> fix: update CNCF registry version to 2.3.4, app version 2.8.3

- .github/workflows/checks.yml
- test/e2e/config/caren.yaml
Also remove Nutanix 1.30 test.
> test(e2e): Nutanix 1.33.1 testing

- docs/content/addons/cni.md
- docs/layouts/shortcodes/mdl-disable.html
Fix broken link in Cilium CNI docs
Fixes #
> docs: Update link to default Cilium values in cni.md

- charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
- hack/addons/helm-chart-bundler/repos.yaml
- make/addons.mk
> feat: update Nutanix CSI to 3.3.4

- cmd/main.go
- go.mod
- go.sum
- pkg/webhook/preflight/generic/checker.go
- pkg/webhook/preflight/generic/registry.go
- pkg/webhook/preflight/generic/registry_test.go
- pkg/webhook/preflight/generic/spec.go
- pkg/webhook/preflight/generic/spec_test.go
https://jira.nutanix.com/browse/NCN-107573
https://jira.nutanix.com/browse/NCN-105405
Fixes #
> feat: adds a generic checker package with registry and mirror  checks

- pkg/webhook/preflight/generic/registry.go
- pkg/webhook/preflight/generic/registry_test.go
The registry check was returning the wrong field in some cases.
Fixes #
> fix: Include correct field name in registry preflight check results

- pkg/webhook/preflight/generic/registry.go
changes name of registry chec
Fixes #
> fix: use a better name for registry check

- pkg/webhook/preflight/generic/registry.go
- pkg/webhook/preflight/generic/registry_test.go
- pkg/webhook/preflight/generic/spec.go
- pkg/webhook/preflight/generic/spec_test.go
- pkg/webhook/preflight/nutanix/credentials.go
- pkg/webhook/preflight/nutanix/credentials_test.go
- pkg/webhook/preflight/nutanix/image.go
- pkg/webhook/preflight/nutanix/image_test.go
- pkg/webhook/preflight/nutanix/specs.go
- pkg/webhook/preflight/nutanix/specs_test.go
- pkg/webhook/preflight/nutanix/storagecontainer.go
- pkg/webhook/preflight/nutanix/storagecontainer_test.go
- pkg/webhook/preflight/preflight.go
- pkg/webhook/preflight/preflight_test.go
Adds more context to preflight check messages.
Fixes #
> feat: Add context to preflight check messages

- pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
When there is a conflict writing the MetalLB configuration, we want to give more information to the user.
Fixes https://jira.nutanix.com/browse/NCN-107584
> feat: Add more context to MetalLB config apply conflict errors

- pkg/webhook/preflight/generic/spec.go
- pkg/webhook/preflight/generic/spec_test.go
- pkg/webhook/preflight/nutanix/credentials.go
- pkg/webhook/preflight/nutanix/failuredomain.go
- pkg/webhook/preflight/nutanix/specs.go
- pkg/webhook/preflight/nutanix/specs_test.go
- pkg/webhook/preflight/nutanix/storagecontainer.go
- pkg/webhook/preflight/nutanix/storagecontainer_test.go
I identified more mistakes in preflight check messages and fields. The fixes are in separate commits. 
Fixes #
> fix: More fixes to preflight result messages and fields

- api/external/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/api/v1beta1/nutanixcluster_types.go
- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/nutanix-cluster-class.yaml
- hack/examples/bases/nutanix/clusterclass/kustomization.yaml.tmpl
- hack/third-party/capx/go.mod
- hack/third-party/capx/go.sum
* Update hack/third-party/capx/go.mod and run `make apis.sync`
* Remove empty `failuredomains` slice from `NutanixClusterTemplate` and run `make examples.sync`
> fix(deps): Update CAPX to v1.7.0

- pkg/webhook/preflight/README.md
Explain how to implement `Check`s and `Checker`s.
Fixes #
> docs: Add dev doc for preflight checks

- .github/workflows/e2e.yml
This is the preferred upstream action and once it is incorporated into
devbox-install-action this can be removed from here too.
Fixes #
> ci: Use DeterminateSystems/nix-installer-action instead of cachix action

- charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/eks-cluster-class.yaml
- hack/examples/bases/eks/clusterclass/clusterclass.yaml
adds details required for al 2023 
stacked on #1332 
> fix: adds ami details for nodeadm configs
